      <div class="section generic">
      <div class="wide-bg" >
        <div class="container">
          <div class="row">
            <!-- Aqui vai o contéudo -->
            <div class="span12">
                <h2>Mensagem</h2>
                <br>
                <p>A seguinte mensagem foi encaminhada a você:</p>
              </div>
            </div>
          </div>
        </div>
      </div>
