<?php
	  $this->headTitle("Webadmin - Detalhes do projeto");

	  Use Application\Model\Project; 

    if (!empty($sMensagemErro)) {
?>
<div id="alerta" class="alert alert-error">
  <button type="button" class="close" onClick="$('#alerta').hide();">&times;</button>
  <strong>Atenção!</strong><br/><br/>
  <?php echo $sMensagemErro ?>
</div>
<?php		
	}
?>	
<div class="span10">

    <h2>Etapa 1 - Pré-aprovação</h2>

    <p>As informações abaixo foram cadastradas pelo autor <strong><?php echo $umAutor->getNome()?></strong> como um PRÉ-PROJETO.</p>
    
        <form class="form" action="<?php echo $this->basePath()?>/wbadmin/projetos-atualizaDados" method="post" id="formProjeto">
            <input type="hidden" name="operacao" id="operacao" value="">
            <input type="hidden" name="project_id" value="<?php echo $umProjeto->getId()?>">
            <input type="hidden" name="status" value="<?php echo $umProjeto->getProperty("status")?>">
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info"><strong>Nome do projeto</strong></label>
                    <div class="controls">
                        <input type="text" id="npNome" name="nome_projeto" placeholder="Entre com o título do projeto" value="<?php echo $umProjeto->getProperty("title")?>"  class="span12">
                    </div>
                </div>
                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npOrganizacao"><strong>Organização</strong></label>
                    <div class="controls">
                        <input type="text" id="npOrganizacao" name="organizacao" placeholder="Entre com o nome da organização" value="<?php echo $umProjeto->getProperty("organization")?>" class="span12">
                    </div>
                </div>
            
                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npEmailContato"><strong>Email de contato</strong></label>
                    <div class="controls">
                        <input type="email" name="email" class="span12" id="npEmailContato" placeholder="E-mail do responsável" value="<?php echo $umProjeto->getProperty("email")?>">
                    </div>
                </div>
                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
<?php
    // Captura os telefones
    $aPhones = $umProjeto->getAllPhones();
?>            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npTelefonePrincipalContato"><strong>Telefone para contato</strong></label>
                    <div class="controls">
                        <input type="text" name="telefone_principal" class="span12 phone_number_mask" id="npTelefonePrincipalContato" placeholder="Telefone principal" value="<?php echo $aPhones["Principal"]?>">
                    </div>
                </div>
                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npTelefoneSecundarioContato"><strong>Outro telefone</strong></label>
                    <div class="controls">
                        <input type="text" name="telefone_secundario" class="span12 phone_number_mask" id="npTelefoneSecundarioContato" placeholder="Caso não encontremos você no outro telefone"  value="<?php echo $aPhones["Outro"]?>"  >
                    </div>
                </div>

                            
                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npNome" style="margin-top: 10px"><strong>Qual o seu tipo jurídico</strong></label>
                    <div class="controls">
<?php
    $aProjectCompanyTypes = $umProjeto->getAllCompanyTypes();
    foreach ($aCompanyTypes as $aValue) { 
        $sAdd = "";
        if (in_array($aValue["id"],$aProjectCompanyTypes)) {
        	$sAdd = " checked";
        }
?>
                            <label class="checkbox">
                                <input type="checkbox" name="tipo_juridico[]" value="<?php echo $aValue["id"]?>" id="npTipoJuridico"<?php echo $sAdd?>><?php echo $aValue["title"]?>
                            </label>
<?php
    } 
?>
                    </div>
                    
                </div>

                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npComoChegouBenfeitoria"><strong>Como chegou até a Benfeitoria?</strong></label>
                    <div class="controls">
                        <textarea rows="4" class="span12" id="npComoChegouBenfeitoria" name="como_chegou_benfeitoria"><?php echo $umProjeto->getProperty("how_find_us")?></textarea>
                    </div>
                </div>

                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npSobreVoce"><strong>Conte-nos um pouco sobre você</strong></label>
                    <div class="controls">
                        <textarea rows="4" class="span12" id="npSobreVoce" name="sobre_voce"><?php echo $umProjeto->getProperty("about_you")?></textarea>
                    </div>
                </div>

                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npResumoProjeto"><strong>Resuma seu projeto</strong></label>
                    <div class="controls">
                        <textarea rows="4" class="span12" id="npResumoProjeto" name="resumo_projeto"><?php echo $umProjeto->getProperty("project_abstract")?></textarea>
                    </div>
                </div>

                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npRegiaoAtuacao"><strong>Região de atuação</strong></label>
                    <div class="controls">
                        <input type="text" class="span12" id="npRegiaoAtuacao" name="regiao_atuacao" placeholder="Descreva a região de atuação de seu projeto (nacional, estadual, nome da cidade, etc.)" value="<?php echo $umProjeto->getProperty("operating_region")?>">
                    </div>
                </div>

                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npTemas" style="margin-top: 10px"><strong>Em quais temas seu projeto se encaixa?</strong></label>
                    <div class-"controls">
<?php
    $aProjectCategories = $umProjeto->getAllCategories();
    foreach ($aCategories as $aValue) { 
        $sAdd = "";
        if (in_array($aValue["id"],$aProjectCategories)) {
            $sAdd = " checked";
        }
?>
                        <label class="checkbox">
                            <input type="checkbox" name="temas[]" value="<?php echo $aValue["id"]?>" id="npTemas"<?php echo $sAdd?>><?php echo $aValue["title"]?>
                        </label>
<?php 
    }
?>
                    </div>
                </div>
                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npAnoFundacao"><strong>Informações gerais da instituição</strong></label>
                    <div class="controls">
                        <div class="for-group col-md-3">
                            <label for="npAnoFundacao"><strong>Ano de fundação</strong></label>
                            <input type="text" class="span12" id="npAnoFundacao" name="ano_fundacao" value="<?php echo $umProjeto->getProperty("fundation_year")?>">
                        </div>
                        <div class="for-group col-md-3">
                            <label for="npNumFuncionarios"><strong>N<sup><u>o</u></sup> de funcionários</strong></label>
                            <input type="text" class="span12" id="npNumFuncionarios" name="num_funcionarios" value="<?php echo $umProjeto->getProperty("employees_number")?>">
                        </div>
                        <div class="for-group col-md-3">
                            <label for="npNumVoluntarios"><strong>N<sup><u>o</u></sup> de voluntários</strong></label>
                            <input type="text" class="span12" id="npNumVoluntarios" name="num_voluntarios" value="<?php echo $umProjeto->getProperty("volunteers_number")?>">
                        </div>
                        <div class="for-group col-md-3">
                            <label for="npNumPessoasImpactadas"><strong>N<sup><u>o</u></sup> de pessoas impactadas</strong></label>
                            <input type="text" class="span12" id="npNumPessoasImpactadas" name="num_pessoas_impactadas" value="<?php echo $umProjeto->getProperty("people_impacted_number")?>">
                        </div>
                    </div>
                </div>
                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npMaisSobre"><strong>Fale um pouco mais sobre o projeto</strong></label>
                    <div class="controls">
                        <textarea rows="4" class="span12" id="npMaisSobre" name="mais_sobre" ><?php echo $umProjeto->getProperty("about_project")?></textarea>
                    </div>
                </div>

                
                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npHaQuantoTempo"><strong>Há quanto tempo o projeto acontece? O que já foi feito?</strong></label>
                    <div class="controls">
                        <textarea rows="4" class="span12" id="npHaQuantoTempo" name="ha_quanto_tempo" ><?php echo $umProjeto->getProperty("how_long")?></textarea>
                    </div>
                </div>
                
                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npGastoMensal"><strong>Qual a média de gastos mensal do projeto hoje? Com quanto ele se sustenta por mês?</strong></label>
                    <div class="controls">
                        <textarea rows="4" class="span12" id="npGastoMensal" name="gasto_mensal" ><?php echo $umProjeto->getProperty("average_monthly_spending")?></textarea>
                    </div>
                </div>
                
                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npRecursosExternos"><strong>O projeto já recebe recursos de alguma outra fonte?</strong></label>
                    <div class="controls">
                        <textarea rows="4" class="span12" id="npRecursosExternos" name="recursos_externos" ><?php echo $umProjeto->getProperty("resources_from")?></textarea>
                    </div>
                </div>

                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" class="control-label" for="npMaisSobre">Metas informadas</label>
                    
<?php
    // Metas
    $aGoals = $umProjeto->getAllGoals();
    $iContGoal = 1;
    foreach ($aGoals as $aGoal) { 
?>
                            <label class="control-label" for="npMaisSobre"><strong>Meta <?php echo $iContGoal?></strong></label>
                                <div class="controls">
                                    <div class="control-group col-md-3">
                                        <label for="npMeta1Valor">Valor</label>
                                        <div class="input-append">
                                            <span class="add-on">R$</span>
                                            <input type="text" name="meta_valor[]" id="npMeta1Valor" class="span7 money" value="<?php echo $aGoal["reference"]?>">
                                            <span class="add-on">,00</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="controls">
                                    <div class="control-group">
                                        <label for="npMeta1ObjetivosValor">O que pretende fazer com este valor?</label>
                                        <textarea rows="4" class="span12" id="npMeta1ObjetivosValor" name="meta_objetivos_valor[]"><?php echo $aGoal["goal"]?></textarea>
                                    </div>
                                </div>
                                <div class="controls">
                                    <div class="control-group">
                                        <label for="npMeta1Recompensa">Recompensa coletiva ao atingir a meta</label>
                                        <textarea rows="4" class="span12" id="npMeta1Recompensa" name="meta_recompensa[]"><?php echo $aGoal["collective_reward"]?></textarea>
                                    </div>
                                </div>
<?php 
        $iContGoal++;
    }
?>
                            </div>

                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info" for="npComoSeraArrecadacao"><strong>Como será feita a arrecadação para o projeto?</strong></label>
                    <textarea rows="4" class="span12" id="npComoSeraArrecadacao" name="como_sera_arrecadacao"><?php echo $umProjeto->getProperty("marketing")?></textarea>
                </div>

                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <fieldset>
                <div class="control-group span8">
                    <label class="control-label text-info"><strong>Links relacionados</strong></label>
<?php
    $aProjectLinks = $umProjeto->getAllLinks();
    foreach ($aProjectLinks as $aLink) { 
?>
                    <div class="controls">
                        <label for="npTitulo">Título</label>
                        <input type="text" name="link_titulo[]" id="npTitulo" class="span12" value="<?php echo $aLink["title"]?>">
                    </div>
                    <div class="controls">
                        <label for="npURL">URL</label>
                        <input type="text" name="link_url[]" id="npURL" class="span12" value="<?php echo $aLink["link"]?>">
                    </div>
<?php
    } 
?>
                    <div class="controls text-left" style="display:none">
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary" id="btnAddLink">Adicionar</button>
                            <button type="button" class="btn btn-danger" id="btnRemoveLink">Remover</button>
                        </div>
                    </div>
                </div>
                <div class="control-group span4">
                    <label class="control-label">Comentários</label>
                    <div class="controls">
                        <a class="btn btn-small" href="#"><i class="icon-plus"></i> Adicionar</a><a class="btn btn-small btn-warning" href="#"><i class="icon-warning-sign"></i> Ler Novos</a>
                    </div>
                </div>
            </fieldset>
            
            <div class="form-actions">
              <button type="button" class="btn btn-primary" onClick="gravarAlteracoes()">Apenas gravar alterações</button>
              <button type="button" class="btn btn-success" onClick="publicarProjeto()">Gravar e PUBLICAR</button>
              <button type="button" class="btn">Cancelar</button>
            </div>   
        </form>
    
</div>

<script>

    function gravarAlteracoes() {
    	$('#operacao').val('gravar');
    	$('#formProjeto').submit();
    }


    function publicarProjeto() {
    	$('#operacao').val('gravar_publicar');
    	$('#formProjeto').submit();
    }
    
</script>
