      <div class="section generic">
      <div class="wide-bg" >
        <div class="container">
          <div class="row">
            <div class="span12">            
                <h2>Cancelado</h2>
              
                <p class="info">Sua assinatura da campanha <?php echo $oProject->getProperty("title")?> foi cancelada.</p>
            </div>
          </div>
        </div>
      </div>
      </div>
         
            
