<?php echo $this->headTitle($oProject->getProperty("title")." | "); ?>

<?php 
    // Ajusta as metas
    $this->headMeta()->appendName('og:locale', 'pt_BR')
                    ->appendName('og:url', htmlspecialchars("//$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]", ENT_QUOTES, 'UTF-8'))
                    ->appendName('og:title', $oProject->getProperty("title")." | Recorrente")
                    ->appendName('og:site_name', 'Recorrente: financiamento contínuo')
                    ->appendName('og:description', $oProject->getProperty("tag_line"))
                    ->appendName('og:image', $this->basePath().($oProject->getProperty("url_cover_image")))
                    ->appendName('og:image:type', 'image/jpeg')
                    ->appendName('og:image:width', '62')
                    ->appendName('og:image:height', '62');
                    
?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=515999545152995&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

        <div class="section saiba-mais about-project">
          <div class="container">
            <div class="row">
              <div class="span8">
                <br>
                <h2><?php echo $oProject->getProperty("title")?></h2>
              </div>
              <div class="span4">
              </div>
              <div class="span2"></div>
            </div>
            <div class="row bottompush">
              <div class="span7">
                <p>
                <?php echo $oProject->getProperty("tag_line")?>
                </p>
              </div>
              <div class="span5"></div>
            </div>
          </div>
        </div>
      
      

      <div class="section informeCampanha">
        <div class="container">
          <div class="row">

            <div class="span8 abasProjeto" style="margin-top:11px;">
              <ul class="nav nav-tabs">
                <li class='active campanha'><a href="#campanha" data-toggle="tab">CAMPANHA</a></li>
                <li class='galeria'><a href="#galeria" data-toggle="tab">GALERIA</a></li>
                <li class='assinantes'><a href="#assinantes" data-toggle="tab" onClick="$('#assinantes').load('<?php echo $this->basePath()?>/projeto/assinantes/<?php echo $oProject->getId()?>')">ASSINANTES</a></li>
                <li class='coments'><a href="#comentarios" data-toggle="tab">COMENTÁRIOS</a></li>
                <li class='novidades'><a href="#novidades" data-toggle="tab">NOVIDADES</a></li>
                <li class='last contas'><a href="#contas" data-toggle="tab" class='last'>PRESTAÇÃO DE CONTAS</a></li>
              </ul>


              <div class="tab-content">
                <div class="tab-pane active" id="campanha">

                    <div class="campanhaWrapper">
                
                    <div class="videocampanha">
                      <?php echo $oProject->getProperty("embed_video")?>
                      <!-- <iframe width="470" height="270" src="#" frameborder="0" allowfullscreen></iframe> -->
                     </div>

                      <div class="socialButtons">
                        
                        <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
                        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<?php 

$link =  "//$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
$escaped_link = htmlspecialchars($link, ENT_QUOTES, 'UTF-8');

?>
                        <div class="fb-like" data-href="<?php echo $escaped_link?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div> </div>
                      <br>

                      <h3><?php echo $oProject->getProperty("title") ?></h3>
                      <p><?php echo $oProject->getProperty("tag_line") ?></p>
                      <h3>Nossa História</h3>
                      <p><?php echo $oProject->getProperty("description") ?></p>
<?php
    if (!$bProjectContributor) {
?>
                      <button class="btn btn-primary" type="button" onClick="contribuir(<?php echo $oProject->getId()?>,'<?php echo $iIdUsuarioLogado?>')">Contribuir <i class="fa fa-arrow-right"></i></button>
<?php 
    }
?>
                    </div>
                </div>
                <div class="tab-pane" id="galeria"><h3>Em breve</h3><br /><br /><br /><br /><br /><br /></div>
                <div class="tab-pane" id="comentarios">

      <div class="fb-comments" style='margin-left:35px' data-href="<?php echo $escaped_link?>" data-numposts="7" data-colorscheme="light"></div>
                </div>
                <div class="tab-pane" id="assinantes"></div>
                <div class="tab-pane" id="novidades"><h3>Em breve</h3><br /><br /><br /><br /><br /><br /></div>
                <div class="tab-pane" id="contas"><h3>Em breve</h3><br /><br /><br /><br /><br /><br /></div>
              </div>
            </div>


            
            <!-- Coluna da direita -->
            
            <div class="span4 sobreArrecadacao">
              <div id="preConteudo">
              <div class="loader" style='display:none'><i class="fa fa fa-spinner fa-spin fa-5x"> </i></div>
              <div id="divConteudo">
              <!-- @TODO: Refatorar isso em divs -->
              <strong class='headline'><span>R$</span> <?php echo number_format($fTotalAmount,2,",",".")?></strong>
              <br>
              <span class='tagline'>arrecadado por mês</span>
              <br><br>
              <img src="<?php echo $this->basePath()?>/v1/img/icon-people.png" > <span class='numberOfPeople'><?php echo $iCountContributor?></span> <span class='assinantes'>assinantes</span>
              <br><br>
<?php
    if (!$bProjectContributor) {
?>
              <button class="btn btn-primary" type="button" style='margin-left:30px' onClick="contribuir(<?php echo $oProject->getId()?>,'<?php echo $iIdUsuarioLogado?>')">Contribuir <i class="fa fa-arrow-right"></i></button>
              <br><br><br>
<?php 
    }
    else {
        $oContribution = $oProject->getUserContribution($iIdUsuarioLogado);
?>
                <div class="jaContribuiu">
                <div class="alert alert-pagamento alert-info alert-contribuiu">
                  <strong>Você já é um assinante desta campanha.</strong>
                  <p>
                     R$<?php echo number_format($oContribution->getProperty("value_contribution"),2,",",".")?> em <?php echo date("d/m/Y",strtotime($oContribution->getProperty("dt_contribution")))?>
                  </p>
              </div>

               <button class="btn btn-primary" type="button" onClick="alterarContribuicao(<?php echo $oProject->getId()?>,'<?php echo $oContribution->getId()?>')">Alterar minha assinatura</i></button>

                <a href="#modalCancelar" role='button' data-toggle='modal'><button class="btn btn-primary" type="button">Cancelar minha assinatura </i></button></a>

              <div id="modalCancelar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalCancelar" aria-hidden="true">
                <div class="modal-header">
                  <!-- button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> -->
                  <h3 id="label">Cancelar</h3>
                  <hr>
                </div>
                <div class="modal-body">
                  <p>Tem certeza que deseja cancelar sua assinatura da campanha <?php echo $oProject->getProperty("title")?></p>
                </div>
                <div class="modal-footer">
                  <button class="btn" onClick="$('#modalConfirmacao').modal('hide'); cancelarContribuicao(<?php echo $oProject->getId()?>,'<?php echo $iIdUsuarioLogado?>','<?php echo $oContribution->getId()?>')">Sim, confirmo</button>
                  <button class="btn" data-dismiss="modal" aria-hidden="true">Não</button>
                </div>
              </div>
            </div>
<?php 
    }
?>
              
              
              
              <hr>
              <br>
              <span class='meta'>Meta atual: R$<?php echo number_format($aActualGoal["reference"],2,",",".")?></span>
              <div class="progress">
                <div class="bar" style="width: <?php echo $fProgress?>%">
                  <!-- <span class="sr-only" style="color:white"> 35% </span> -->
                </div>
              </div>

              <ul>
                  <li><span><?php echo $aActualGoal["goal"]?></span></li>
                  <li><span>Recompensa:<br/><?php echo $aActualGoal["collective_reward"]?></span></li>
                  </ul>
<?php 
    // Metas alcançadas
    $aAllGoals = $oProject->getAllGoals();
    foreach ($aAllGoals as $aGoal) {
        if ($aGoal["reference"]<$fTotalAmount) {
?>

              <span class='meta alcancada'>Meta alcançada</span><img class='check' src="<?php echo $this->basePath()?>/v1/img/checked.png">
              <br>

              <ul>
                  <li><span>- <?php echo $aGoal["goal"]?></span></li>
              </ul>

<?php            
        }
    }
?>

               <div class="accordion" id="metaAccordion">
                      <div class="accordion-group">
                        <div class="accordion-heading">
                          <a class="accordion-toggle" data-toggle="collapse" data-parent="#metaAccordion" href="#collapseOne">
                            
                            <button class="btn btn-primary" id="verMetas" type="button">VER TODAS AS METAS <i class="fa fa-caret-down"></i>  </button>
                          </a>
                        </div>
                        <div id="collapseOne" class="accordion-body collapse">
                          <div class="accordion-inner">
                            
<?php 
    foreach ($aAllGoals as $aGoal) {
        if ($aGoal["reference"]<$fTotalAmount) {
?>
                          <span class='meta alcancada'>Meta: R$ <?php echo number_format(str_replace(".","",$aGoal["reference"]),2,",",".")?></span><img class='check' src="<?php echo $this->basePath()?>/v1/img/checked.png">
<?php             
        }
        else {
?>
                          <span class='meta alcancada'>Meta: R$ <?php echo number_format(str_replace(".","",$aGoal["reference"]),2,",",".")?></span>
<?php             
        }
?>
                            <br>
                            <ul>
                              <li><span><?php echo $aGoal["goal"]?><br/><br/>Recompensa: <?php echo $aGoal["collective_reward"]?></span></li>
                            </ul>
<?php
    } 
?>                            
                            
                          </div>
                        </div>
                      </div>
                    </div>
</div> </div>
                <!-- </div> -->

                  <div class="span4 anotherBox pull-right">
                    <div class="wrapProjetistaInfo">
                    <div class="img">
                      <img src="<?php echo $this->basePath().($oProjectOwner->getFoto("medium"))?>" width="62" alt="<?php echo $oProjectOwner->getNome()?>">
                    </div>
                    <div class="about">
                      <ul>
                        <li><span><?php echo $oProjectOwner->getNome()?></span></li>
<?php 
    $aCategories = $oForm->getCategories();
    $aQuickCategories = array();
    foreach ($aCategories as $aTemp) {
        $aQuickCategories[$aTemp["id"]] = $aTemp["title"];
    }
    $aProjectCategories = $oProject->getAllCategories();
    $sCategoriesList = "";
    foreach ($aProjectCategories as $iCategoryId) {
        if (!@empty($aQuickCategories[$iCategoryId])) {
            $sCategoriesList .= $aQuickCategories[$iCategoryId].", ";
        }
    }
    if (strlen($sCategoriesList)>0) {
        $sCategoriesList = substr($sCategoriesList,0,-2);
    }
?>
                        <li><span>Categoria: <?php echo $sCategoriesList?></span></li>
<?php
    if (($oProject->getProperty("about_you")!="")) { 
?>
                        <li><span>Descrição: <?php echo $oProject->getProperty("about_you")?></span></li>
<?php
    } 
?>
                        </ul>
                    </div>
                    <br>
                    </div>
                  </div>
                  <?php
    $aUsers = $oProject->getLastContributors(10);
    if (count($aUsers)>0) { 
?>
          <div class="span4 anotherBox pull-right">
                  <h4>Últimos Assinantes</h4>
                  
              <div class="assinantesPrev">
<?php
    foreach ($aUsers as $oUser) { 
?>
                <div class="square"><img title='<?php echo $oUser->getNome() ?>' src="<?php echo $this->basePath().($oUser->getFoto("small"))?>" alt="<?php echo $oUser->getNome()?>"></div>
<?php
    } 
?>
              </div>                  
              <br>
            </div>
             
<?php 
    }
?>

          </div>

           
              
        
           
        </div>
      </div>
    </div>

    <script src="<?php echo $this->basePath()?>/v1/js/vendor/prettyphoto/jquery.prettyPhoto.js" type="text/javascript"></script>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function(){
        $("a[rel^='prettyPhoto']").prettyPhoto({
        default_width: 600,
        default_height: 544,
        show_title: true,
        theme: 'light_square'
        });
        });
    </script>
        