<!DOCTYPE html>
<html lang="pt_Br" xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
  <meta charset="UTF-8">
<?php
  // Meta
  echo $this->headMeta()->appendName("description", "O Recorrente é uma ferramenta da Benfeitoria, destinada a iniciativas que buscam financiamento contínuo.")
  														->appendName("keywords", "recorrente, crowdfunding, financiamento coletivo, crowdfunding contínuo, assinatura, benfeitoria, colaboração, wikinomia, impacto, artistas, coletivos, ong, negocios sociais, empreendedorismo, financiamento, arrecadação, recursos, mensalidade")
  														->appendName("robots", "index, follow");
  // Title
	echo $this->headTitle("Recorrente: financiamento contínuo");
?>
  <link type="text/plain" rel="author" href="./humans.txt" />
  <link href="http://fonts.googleapis.com/css?family=Oswald:400,300" rel="stylesheet" type="text/css" media="screen" />
  <link href="<?php echo $this->basePath()?>/v1/css/style.css" rel="stylesheet" type="text/css" media="screen" />
  <link href="<?php echo $this->basePath()?>/v1/css/recorrente.css" rel="stylesheet" type="text/css" media="screen" />
  <link rel="shortcut icon" href="<?php echo $this->basePath()?>/favicon.ico" type="image/x-icon">
  <link rel="icon" href="<?php echo $this->basePath()?>/favicon.ico" type="image/x-icon">
</head>
<body>

    <!-- Vendor Scripts -->
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/jquery.min.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/bootstrap/bootstrap.min.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/bxslider/jquery.bxslider.min.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/theme/masonry.min.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/theme/fancybox.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/theme/functions.js" type="text/javascript"></script>
    <!--  Project Scripts -->
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/jquery.validate.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/jquery-validation-1.12.0/src/localization/messages_pt_BR.js"></script>
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/jquery.mask.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/jquery.maskMoney.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/jquery.limit-1.2.source.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/cropbox-min.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/jquery.mousewheel.min.js" type="text/javascript"></script>
    
    <script src="<?php echo $this->basePath()?>/v1/js/vendor/qtip.min.js" type="text/javascript"></script>

  <div class="riomais-toolbar">
    <div id="logo-benfeitoria"><a href="http://benfeitoria.com" target="_blank">Benfeitoria</a></div>
    <div id="slogan">Mobilização para projetos de impacto</div>
  </div>

  <div id="wrap">
    <div class="section">
      <div class="container">
        <div class="row">

          <div class="span4">
            <p class='wraplogo'><a href="#">
              <a href="<?php echo $this->basePath()?>/"><img src="<?php echo $this->basePath()?>/v1/img/logo-recorrente-beta.png" alt="logo-recorrente"></a>
              </a>
            </p>
          </div>

          <div class="span8 text-right">
            <div class="navbar pull-right">
              <ul class="nav navbar-nav" id="divMenuContent">
              </ul>
            </div>
          </div>

        </div>
      </div>
    </div>


    <div id="pageContent">
        <?php echo $this->content; ?>
    </div>


    <footer>
      <div class="footer">
        <div class="container">
          <div class="row">
            <div class="span3">
              <h3>RECORRENTE</h3>
              <ul>
                <li><a href="<?php echo $this->basePath()?>/comoFunciona" style="color:#ffffff">Como Funciona</a></li>
                <li><a href="<?php echo $this->basePath()?>/campanhas" style="color:#ffffff">Campanhas</a></li>
                <li><a href="<?php echo $this->basePath()?>/arrecade" style="color:#ffffff">Arrecade</a></li>
                <li><a href="<?php echo $this->basePath()?>/faq" style="color:#ffffff">FAQ</a></li>
                <li><a href="<?php echo $this->basePath()?>/termosUso" style="color:#ffffff">Termos de uso</a></li>
                <li><a href="<?php echo $this->basePath()?>/contato" style="color:#ffffff">Fale conosco</li>
              </ul>
            </div>
            <div class="span1"></div>
            <div class="span3">
              <h3>BENFEITORIA</h3>
              <ul>
                <li><a href="http://benfeitoria.com/nossa-proposta" target="_blank" style="color:#ffffff">Quem somos</a></li>
                <li><a href="http://www.benfeitoria.com" target="_blank" style="color:#ffffff">Crowdfunding</a></li>
                <li><a href="http://www.facebook.com/benfeitoria" target="_blank" style="color:#ffffff">Facebook</a></li>
                <li><a href="http://riomais.benfeitoria.com" target="_blank" style="color:#ffffff">Rio+</a></li>
              </ul>
            </div>
            <div class="span1"></div>
          </div>
        </div>
      </div>
    </footer>


    <script>
    	$(function() {
  		    sBasePath = '<?php echo $this->basePath()?>';
        	var sLoggedUserId = '<?php echo $iIdUsuarioLogadoSite?>';
        	if (sLoggedUserId!='') {
        		$('#divMenuContent').load(sBasePath+'/ajaxV1HeaderLogged/u=<?php echo base64_encode($_SERVER['REQUEST_URI'])?>');
        	}
        	else {
        		$('#divMenuContent').load(sBasePath+'/ajaxV1HeaderLogin/u=<?php echo base64_encode($_SERVER['REQUEST_URI'])?>');
     		  }
      });
    </script>

    <script src="<?php echo $this->basePath()?>/v1/js/core.js" type="text/javascript"></script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-55277501-1', 'auto');
      ga('require', 'displayfeatures');
      ga('send', 'pageview');

    </script>
</body>
</html>
