<div class="span2">
    <div class="well sidebar-nav">
        <ul class="nav nav-list">
            <li class="nav-header">Projetos</li>
            <li><a href="<?php echo $this->basePath()?>/wbadmin/projetos-moderacao">Moderação</a></li>
<!--             <li><a href="#">Gerar conceitos de teste</a></li> -->
<!--             <li><a href="#">Eliminar conceitos de teste</a></li> -->
<!--             <li class="nav-header">Tabelas de Apoio</li> -->
<!--             <li><a href="/manutencao/tabelasApoio-NormatizarNomes">Normatizar _nomes</a></li> -->
<!--             <li><a href="/manutencao/tabelasApoio-TabelasBase">Atualiza tabelas-base</a></li> -->
            <li class="nav-header">Website CFC</li>
            <li><a href="<?php echo $this->basePath()?>/wbadmin/relatorio/">Relatórios</a></li>
            <li><a href="<?php echo $this->basePath()?>/">Retornar a Home</a></li>
            <!--  class="active" -->
        </ul>
    </div>
</div>
