<?php include ("webadmin-topo.phtml"); ?>

    <div class="container-fluid">
      <div class="row-fluid">

<?php include ("webadmin-menu.phtml"); ?>

      <div class="span9">


<!-- Conteudo da pagina -->
<?php echo $this->content; ?>
<!-- Fim conteudo -->


        </div><!--/span-->
      </div><!--/row-->

      <hr>
      <footer>
        <p>&copy; Benfeitoria</p>
      </footer>

    </div>

</body>
</html>
