<?php echo $this->doctype(); ?>
<html lang="en">
  <head>

<?php
	// Meta dados
  echo $this->headMeta()->appendName("viewport", "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
  														->appendName("apple-mobile-web-app-capable", "yes")
  														->appendName("apple-mobile-web-app-status-bar-style", "black-translucent")
                              ->appendName("charset","utf-8");
	
	echo "\n\n";
	
	// Title
	echo $this->headTitle( $this->translate('titulo login'))->setSeparator(' - ')->setAutoEscape(false); 
	echo "\n\n";
	
	// CSS
	$this->headLink(array("rel" => "apple-touch-icon-precomposed", "href" => $this->basePath() . "/mnt/img/apple-touch-icon-precomposed.png"));
	echo $this->headLink(array("rel" => "shortcut icon", "type" => "image/vnd.microsoft.icon", "href" => $this->basePath() . "/mnt/img/favicon.ico"))
                        ->appendStylesheet($this->basePath() . "/mnt/css/bootstrap.css")
                        ->appendStylesheet($this->basePath() . "/mnt/css/bootstrap-responsive.css");
	
	echo "\n\n";
?>
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>
<?php
	
	// JS
	echo $this->headScript()->appendFile($this->basePath() . "/mnt/js/jquery.js")
	                        ->appendFile($this->basePath() . "/mnt/js/bootstrap.js");

	echo "\n\n";
	
?>


  </head>

  <body>

    <div class="container">

<!-- Conteudo da pagina -->
<?php echo $this->content; ?>
<!-- Fim conteudo -->

      <form class="form-signin" action="<?php echo $this->basePath()?>/wbadmin/validaLogin" method="post">
        <h2 class="form-signin-heading">Acesso Restrito</h2>
        <input name="usuario" type="text" class="input-block-level" placeholder="Usuário">
        <input name="senha" type="password" class="input-block-level" placeholder="Senha">
        <label class="checkbox">
          <input type="checkbox" name="lembrar" value="Lembrar-me"> Lembrar-me por 10 dias
        </label>
        <button class="btn btn-large btn-primary" type="submit">Entrar</button>&nbsp;<button class="btn btn-large btn-warning" type="button" onClick="document.location='<?php echo $this->basePath()?>/'">Ir para CFC</button>
      </form>

    </div> <!-- /container -->

  </body>
</html>
