    <div class="page-header">
      <div class="container">
        <h1>Meu perfil</h1>
        <p>Para sua comodidade em futuras contribuições aos projetos, mantenha seus dados sempre atualizados, informando os campos abaixo:</p>
      </div>
    </div>

    <div class="container">
      <div class="rows">
        <div class="col-md-12">

  <form action="<?php echo $this->basePath()?>/atualizaCadastro" method="post" class="form-horizontal" role="form" id="formAtualizaCadastroUsuario">
  <input type="hidden" name="tipo" value="<?php echo $oUser->getTipo()?>">
  <input type="hidden" name="id_usuario" value="<?php echo $oUser->getId()?>">
  
  
  <div class="form-group">
    <label for="inputEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-9">
      <p><?php echo $oUser->getEmail()?></p>
    </div>
  </div>

  <div class="form-group">
    <label for="inputNomeCompleto" class="col-sm-2 control-label">Nome completo</label>
    <div class="col-sm-9">
      <input type="text" name="nome" class="form-control" id="inputNomeCompleto" placeholder="Informe seu nome" value="<?php echo $oUser->getNome()?>" required>
    </div>
  </div>

  <div class="form-group">
    <label for="inputSenha1" class="col-sm-2 control-label">Nova senha</label>
    <div class="col-sm-3">
      <input type="password" name="senha1" class="form-control" id="inputSenha1" placeholder="Senha" required>
    </div>
    <label for="inputSenha1" class="col-sm-2 control-label">Repetir senha</label>
    <div class="col-sm-4">
      <input type="password" name="senha2" class="form-control" id="inputSenha2" placeholder="Senha"  equalto="#inputSenha1" class="required error">
    </div>
    </div>

  <div class="form-group">
    <label for="inputSexo" class="col-sm-2 control-label">Sexo</label>
    <div class="col-sm-9">
        <select name="sexo" id="inputSexo" class="form-control" required>
          <option value="">Escolha -----></option>
          <option value="1" <?php if ($oUser->getSexo()==1) { echo "selected"; }?>>Masculino</option>
          <option value="2">Feminino</option>
        </select>
    </div>
  </div>


  <div class="form-group">
    <label for="inputDataNascimento" class="col-sm-2 control-label">Data de Nascimento</label>
    <div class="col-sm-2 col-md-2">
<?php 
    $sDataNascimento = date("d/m/Y",$oUser->getDataNascimento());
    if ($sDataNascimento=="30/11/-0001") {
        $sDataNascimento = "";
    }
?>
        <input type="text" name="data_nascimento" class="form-control" id="inputDataNascimento" placeholder="__/__/____" value="<?php echo $sDataNascimento?>">
    </div>
  </div>
<?php 
    // Conforme o tipo, apresenta os campos necessários
    if (strtolower($oUser->getTipo())=="pf") {
        // PESSOA FÍSICA
?>
  <div class="form-group">
    <label for="inputCPF" class="col-sm-2 control-label">CPF</label>
    <div class="col-sm-3 col-md-2">
        <input type="text" name="cpf" class="form-control" id="inputCPF" placeholder="" value="<?php echo $oUser->getCPF()?>">
    </div>
  </div>
<?php
    }
    else {
        // PESSOA JURIDICA
?>
  <div class="form-group">
    <label for="inputCNPJ" class="col-sm-2 control-label">CNPJ</label>
    <div class="col-sm-3 col-md-2">
        <input type="text" name="cnpj" class="form-control" id="inputCNPJ" placeholder="" value="<?php echo $oUser->getCNPJ()?>">
    </div>
  </div>
  <div class="form-group">
    <label for="inputCompanyName" class="col-sm-2 control-label">Nome da Empresa</label>
    <div class="col-sm-3 col-md-2">
        <input type="text" name="nome_empresa" class="form-control" id="inputCompanyName" placeholder="" value="<?php echo $oUser->getCompanyNameJ()?>">
    </div>
  </div>
<?php
    }
?>
  <div class="form-group">
    <label for="inputPais" class="col-sm-2 control-label">País</label>
    <div class="col-sm-9">
        <select name="pais" id="inputPais" class="form-control" onChange="selecionaPais($('#inputPais').val())" required>
            <option value="">Escolha -----></option>
<?php echo $sHTMLCountries?>
        </select>
    </div>
    <div class="col-sm-1" id="divLoadingPais">
        <img src="<?php echo $this->basepath()?>/images/loader.gif">
    </div>
  </div>
  
  <div class="form-group" id="divInputEstado">
    <label for="inputNovoEstado" class="col-sm-2 control-label">Estado</label>
    <div class="col-sm-9">
      <input type="text" name="novo_estado" class="form-control" id="inputNovoEstado" placeholder="Informe o estado/território">
    </div>
  </div>

  <div class="form-group" id="divSeletorEstado">
    <label for="inputEstado" class="col-sm-2 control-label">Estado</label>
    <div class="col-sm-9">
        <select name="estado" id="inputEstado" class="form-control" onChange="selecionaCidade($('#inputEstado').val())">
            <option value="">Escolha -----></option>
<?php echo $sHTMLStates?>
        </select>
    </div>
    <div class="col-sm-1" id="divLoadingEstado">
        <img src="<?php echo $this->basepath()?>/images/loader.gif">
    </div>
    </div>
  
  <div class="form-group" id="divInputCidade">
    <label for="inputNovaCidade" class="col-sm-2 control-label">Cidade</label>
    <div class="col-sm-9">
      <input type="text" name="nova_cidade" class="form-control" id="inputNovaCidade" placeholder="Informe a cidade">
    </div>
  </div>
  
  <div class="form-group" id="divSeletorCidade">
    <label for="inputCidade" class="col-sm-2 control-label">Cidade</label>
    <div class="col-sm-9">
        <select name="cidade" id="inputCidade" class="form-control">
            <option value="">Escolha -----></option>
<?php echo $sHTMLCities?>
        </select>
    </div>
    <div class="col-sm-1" id="divLoadingCidade">
        <img src="<?php echo $this->basepath()?>/images/loader.gif">
    </div>
  </div>
<?php 
    $aEndereco = $oUser->getEndereco("residencial");
?>
  
  <div class="form-group">
    <label for="inputEnderecoCompleto" class="col-sm-2 control-label">Endereço completo</label>
    <div class="col-sm-9 col-md-9">
        <input type="text" name="endereco_completo" class="form-control" id="inputEnderecoCompleto" placeholder="" value="<?php echo $aEndereco["address"]?>">
    </div>
  </div>
 
   <div class="form-group">
    <label for="inputCEP" class="col-sm-2 control-label">CEP</label>
    <div class="col-sm-3 col-md-2">
        <input type="text" name="cep" class="form-control" id="inputCEP" placeholder="" value="<?php echo $aEndereco["zip"]?>">
    </div>
  </div>
  
  
  <div class="form-group">
    <div class="col-sm-2">
        &nbsp;
    </div>
    <div class="col-sm-9 text-right">
      <button type="button" class="btn btn-warning">Voltar</button>
      <button type="button" class="btn btn-success" onClick="$('#formAtualizaCadastroUsuario').submit()">Atualizar</button>
    </div> 
  </div>
  
 
  
  
  
</form>
        
        
        
        
        </div>
    </div>
    
    
    <script>
    $(function() {
        if ($('#inputEstado').val()!='') {
            $('#divSeletorEstado').show();
        }
        if ($('#inputCidade').val()!='') {
            $('#divSeletorCidade').show();
        }
    });
    </script>        
    
    