<?php echo $this->headTitle("Contato | Recorrente: financiamento contínuo"); ?>

      <div class="section generic">
      <div class="wide-bg" >
        <div class="container">
          <div class="row">
            <!-- Aqui vai o contéudo -->
            <div class="span12 faqPage contato">
                <h2> Fale Conosco </h2>
                <hr>
                <p>É muito importante pra gente ouvir o que você tem a dizer! Estamos sempre em busca de melhorias, então a sua sugestão, crítica, elogio ou pergunta pode nos ajudar a fazer o Recorrente ser cada vez melhor.</p>

                <p>Escreve pra gente em <a href="mailto:recorrente@benfeitoria.com" target="_top"><span>recorrente</span>@benfeitoria.com</a></p>
                
            </div>
          </div>
         </div>
        </div>
        </div>
      </div>
