<?php echo $this->headTitle("Como Funciona | Recorrente: financiamento contínuo"); ?>

      <div class="section generic">
      <div class="wide-bg" >
        <div class="container">
          <div class="row">
            <!-- Aqui vai o contéudo -->
            <div class="span12">
              <div class="pagePadrao">
                <h2>Como funciona?</h2>
                <br>
                <p>O Recorrente é uma ferramenta da <a href="http://benfeitoria.com/">Benfeitoria</a>, destinada a iniciativas que buscam <strong>financiamento contínuo</strong>. A partir de uma rede de apoiadores contribuindo todo mês com um determinado valor, queremos construir uma política de sustentabilidade para diferentes instituições, ONGs, artistas, coletivos, negócios sociais, etc. A ideia central é transformar essa rede - de envolvidos, entusiastas, simpatizantes - em sujeitos ativos e protagonistas \o/</p>
               
                <p>Não estamos falando aqui de projetos pontuais, mas de um modelo de assinatura mensal que possibilita dar continuidade e potencializar trabalhos super interessantes e benfeitores que já acontecem hoje, aumentando ainda mais o seu poder de impacto! </p>

                <p>Para começar a campanha de arrecadação, toda iniciativa que utilizar o <strong>Recorrente</strong> precisa estabelecer metas mensais que deseja atingir. Para cada meta, existe uma proposta do que será feito com aquele dinheiro. Essa é uma forma de garantirmos transparência durante todo o processo, afinal, nenhum plano de engajamento pode ter sucesso sem que haja confiança, né?
                </p>

                <p>
                  Conforme mais pessoas se tornarem assinantes mensais naquela campanha, as metas vão sendo atingidas uma a uma. E, para cada meta batida, haverá uma celebração, claro! Uma recompensa coletiva oferecida pelos organizadores da campanha a todos que colaboraram até ali, para marcar esse momento tão importante.
                </p>
  
                <p>
                   Mas com quanto contribuir? Na página de cada campanha damos algumas sugestõe$, mas há um campo livre onde o usuário pode definir o valor da sua contribuição mensal. Esse valor pode ser alterado na página do perfil do assinante. Assim, quem tiver naquele mês apertado pode contribuir com menos e quem tá passando por uma maré alta pode dar um pouquinho mais :)
                </p>

                <p>
                  Ah! Sugerimos aos responsáveis pelas campanhas que, independente do valor de contribuição, a recompensa seja coletiva e igual para todos os elos dessa corrente! Mais do que dar importância a cada um dos apoiadores individualmente, queremos celebrar o poder da rede - e a intenção é  expandir cada vez mais!
                </p>
                
                <p>
                  E como a Benfeitoria atua nisso tudo? Nós fazemos a ponte entre iniciativas e apoiadores a partir da criação de um ambiente favorável para essa troca. Além disso, damos suporte no planejamento e manutenção das campanhas na plataforma. O desafio é criar uma rede entre as próprias iniciativas, onde cada uma potencialize a outra e compartilhe valor, formando uma corrente de transformação!
                </p>

                <p>
                  
Para dúvidas ou mais informações, escreva pra gente: <em>recorrente@benfeitoria.com</em><br>
E seja bem-vindo ao Recorrente!
                </p>
                </div><!-- /.pagePadrao -->
              </div>
            </div>
          </div>
        </div>
      </div>
