<?php echo $this->headTitle("Crowdfunding x Recorrente | Recorrente: financiamento contínuo"); ?>

      <div class="section generic">
      <div class="wide-bg" >
        <div class="container">
          <div class="row">
            <!-- Aqui vai o contéudo -->
            <div class="span12 faqPage">
                <h2> Crowdfunding x Recorrente</h2>
                <br>
                
                <img src="<?php echo $this->basePath()?>/v1/img/recxcf.jpg" alt="Recorrente versus Crowdfunding, entenda.">

            </div>
          </div>
         </div>
        </div>
        </div>
      </div>
