
  <div class="section login">
    <div class="container">
      <div class="row">
        <div class="span12">
          <h2 class='lead'>Cadastro de novo usuário</h2>
          <hr>
        </div>
      </div>
      
      <div class="alert alert-warning hide" id="divMensagemSucesso"><h4>Email de confirmação reenviado com sucesso!</h4></div> 
      
      <div class="row getdown">
        <div class="span6">
          <form action="<?php echo $this->basePath()?>/seguro/validaLogin" method="post">
          <h3>Já tenho cadastro</h3> <br> <br>
          <label>
              <input type="text" id='login_mail' placeholder='Informe seu email' name="usuario">
            </label>
            <label>
              <input type="password"  id='login_senha' placeholder='Senha' name="senha">
            </label>
            <a href="<?php echo $this->basePath()?>/seguro/recuperarSenha">Esqueci minha senha</a>
            <input class="btn btn-primary" type="submit" name="#" value="Entrar" /><br/>
            <a href="#" onClick="$('#modalPoliticaPrivacidade').modal({'backdrop':'static'});">Não recebi meu email de ativação</a>
            </form>
        </div>

        <div class="span6">
          <div class="semcadastro">
          <h3>Não tenho cadastro ainda</h3><br>
          <em>Escolha qual o tipo de seu perfil: </em> <br>
          <br>
           <a href="<?php echo $this->basePath()?>/cadastroPJ"><button class="btn btn-primary">Pessoa Jurídica</button></a>
           <br> <br>
           <a href="<?php echo $this->basePath()?>/cadastroPF"><button class="btn btn-primary">Pessoa Física</button></a>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>

    <div id="push"></div>
    
    

<div id="modalPoliticaPrivacidade" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalPoliticaPrivacidade" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Reenviar email de ativação de cadastro</h3>
  </div>
  <div class="modal-body">
    <div style="height:400px;overflow-y:auto">
    <p>
        Caso não tenha recebido o email de ativação de seu novo cadastro, verifique se o mesmo não encontra-se em sua caixa de spam. O título do mesmo é <strong>Bem vind@ ao Recorrente</strong>.<br/>
        <br/>
        Se desejar receber o email novamente, informe abaixo:<br/>
            <form action="@" method="post" class="form-horizontal" role="form" id="formRecuperarEmail">
            <div class="control-group">
              <label  class='control-label' for='email'> Email cadastrado </label>
              <div class="controls">
                <input type="email" id='email' placeholder='Informe' name="email" required onChange="verificaEmailReenvio('<?php echo $this->basePath()?>/ajaxVerificaEmail',$('#email').val())">
                <input type="hidden" name="email_existe" id="emailExiste" value="">
                <span id="spanMensagemErro"></span>
              </div>
              <div class="col-sm-1" id="divLoadingEmail"><img src="<?php echo $this->basepath()?>/images/loader.gif"></div>
            </div>
                </form>
    
    
    </p>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
    <button class="btn btn-primary" id="btnReenvio" disabled onClick="reenviaEmailValidacao($('#email').val())">Reenviar</button>
  </div>
</div>    