<?php echo $this->headTitle("FAQ | Recorrente: financiamento contínuo"); ?>

      <div class="section generic">
      <div class="wide-bg" >
        <div class="container">
          <div class="row">
            <!-- Aqui vai o contéudo -->
            <div class="span12 faqPage">
                <h2> FAQ - Perguntas Frequentes</h2>
                <br>
                

                <div class="accordion" id="accordionFAQ">
                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse1">
                      Quem somos?
                    </a>
                  </div>
                  <div id="collapse1" class="accordion-body collapse">
                    <div class="accordion-inner">
                      Somos a Benfeitoria, uma empresa social com 3 anos de existência, e criamos "experimentos colaborativos", que são plataformas, ferramentas ou conteúdos que nos ajudam a realizar projetos de impacto junto com outras pessoas incríveis. O Recorrente é uma dessas empreitadas e pretende ser uma plataforma para apoiar de forma contínua projetos transformadores.
                    </div>
                  </div>
                </div>
                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse2">
                      O que queremos?
                    </a>
                  </div>
                  <div id="collapse2" class="accordion-body collapse">
                    <div class="accordion-inner">
                      Queremos fomentar uma cultura e uma economia baseada no cuidado, na criatividade e na colaboração. Através do Recorrente queremos ajudar iniciativas incríveis a estreitar a sua relação com as suas redes, assim como gerar uma conexão entre estas iniciativas, numa grande corrente de realização.
                    </div>
                  </div>
                </div>

                 <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse3">
                      Por que queremos?
                    </a>
                  </div>
                  <div id="collapse3" class="accordion-body collapse">
                    <div class="accordion-inner">
                      Não seria muito mais excitante viver num mundo onde a gente conseguisse se conectar com iniciativas e propósitos que nos representam? A gente também acha. Só por isso que estamos aqui.
                    </div>
                  </div>
                </div>

                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse4">
                      Como faremos?
                    </a>
                  </div>
                  <div id="collapse4" class="accordion-body collapse">
                    <div class="accordion-inner">
                      Ihhhh... Aí depende! Se você quer saber da Benfeitoria, a gente faz de tudo! Por isso, vamos focar só no Recorrente aqui, ok? A plataforma vai ser um ponto de encontro entre iniciativas incríveis que buscam recursos e pessoas interessantes que querem fazer parte. No Recorrente, vamos criar uma assinatura mensal, onde essas iniciativas poderão dar início a uma política de sustentabilidade que envolva os apoiadores como agentes protagonistas, começando pelo financiamento contínuo. Entendeu o nome agora?
                    </div>
                  </div>
                </div>
                
                 <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse5">
                      Posso fazer uma única contribuição pontual?
                    </a>
                  </div>
                  <div id="collapse5" class="accordion-body collapse">
                    <div class="accordion-inner">
                      As contribuições no Recorrente serão apenas no formato de assinatura mensal. No entanto, se você gostaria de conhecer projetos de impacto que, para saírem do papel, contam com orçamento e prazo definidos, você pode entrar no site da Benfeitoria <a href="http://benfeitoria.com">benfeitoria.com</a> e conhecer os projetos que estão atualmente no ar!
                    </div>
                  </div>
                </div>

                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse6">
                      O que queremos?
                    </a>
                  </div>
                  <div id="collapse6" class="accordion-body collapse">
                    <div class="accordion-inner">
                     A longo prazo, dominar o mundo. Mas a curto prazo, gerar e compartilhar valor em uma rede de iniciativas bacanas e transformadoras, conectando elas a pessoas incríveis e outras iniciativas, além de levantar uma graninha, claro.
                    </div>
                  </div>
                </div>
                
                 <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse7">
                      Como posso apoiar uma iniciativa?
                    </a>
                  </div>
                  <div id="collapse7" class="accordion-body collapse">
                    <div class="accordion-inner">
                     Teremos várias campanhas abertas no site, buscando assinantes para conseguir dar continuidade a realização dos seus planos. É só entrar na página de uma das campanhas e apoiar com um valor mensal. Divulgar sempre ajuda também, claro!
                    </div>
                  </div>
                </div>
                  <hr>
                  <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse8">
                      Quais formas de pagamento posso usar?
                    </a>
                  </div>
                  <div id="collapse8" class="accordion-body collapse">
                    <div class="accordion-inner">
                     Por enquanto, só cartão de crédito. Depois, prevemos a utilização de PayPal e Débito bancário. Boleto só se você prometer que vai pagar todo mês, tá?
                    </div>
                  </div>
                </div>


                  <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse9">
                      Posso escolher por quantos meses vou fazer o apoio?
                    </a>
                  </div>
                  <div id="collapse9" class="accordion-body collapse">
                    <div class="accordion-inner">
                     A assinatura é contínua, ou seja, vai ficar valendo até que seja cancelada por você ou por algum outro motivo, como por exemplo a falta de pagamento. Mas a gente sabe que você não vai fazer isso, né?
                    </div>
                  </div>
                </div>
    
              <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse10">
                      Como e quando será feita a cobrança?
                    </a>
                  </div>
                  <div id="collapse10" class="accordion-body collapse">
                    <div class="accordion-inner">
                     Uma vez ao mês, o valor da contribuição escolhido por você será cobrado no seu cartão de crédito. Não se preocupe que sempre vai chegar um e-mail para você informando essa operação.
                    </div>
                  </div>
                </div>
              
              <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse11">
                      Posso modificar o valor da minha assinatura?
                    </a>
                  </div>
                  <div id="collapse11" class="accordion-body collapse">
                    <div class="accordion-inner">
                     Claro! É bem fácil! É só ir na página da própria campanha ou nas  <a href="#"> Minhas Assinaturas.</a>
                    </div>
                  </div>
              </div>

               <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse12">
                     Como faço para cancelar meu apoio?
                    </a>
                  </div>
                  <div id="collapse12" class="accordion-body collapse">
                    <div class="accordion-inner">
                     É só entrar na página da própria campanha ou nas <a href="">Minhas Assinaturas.</a> Lá você pode modificar o valor ou cancelar a qualquer momento!
                    </div>
                  </div>
              </div>

               <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse14">
                     Como faço para conferir todo o dinheiro que me foi cobrado?
                    </a>
                  </div>
                  <div id="collapse14" class="accordion-body collapse">
                    <div class="accordion-inner">
                     A página <a href="#">Minhas Assinaturas</a> tem o histórico de tudo que já cobramos de você na vida! Se surgir alguma dúvida, entre em contato com a gente no email recorrente@benfeioria.com.
                    </div>
                  </div>
              </div>
              
              <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse15">
                     O que eu ganho em troca do apoio realizado?
                    </a>
                  </div>
                  <div id="collapse15" class="accordion-body collapse">
                    <div class="accordion-inner">
                     Além de um sorriso no rosto e uma sensação de dever cumprido, uma série de benefícios e recompensas oferecidos por cada campanha. As recompensas são celebrações vinculadas às metas. Já os benefícios podem ser a participação numa reunião, acesso a informações sigilosas, direito a voto em uma questão de vida ou morte e por aí vai... Como esses itens variam de campanha para campanha, vale dar uma conferida na página daquela que você mais curtir.
                    </div>
                  </div>
              </div>

               <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse16">
                    Qual a diferença do crowdfunding para o Recorrente (crowdfunding contínuo)?
                    </a>
                  </div>
                  <div id="collapse16" class="accordion-body collapse">
                    <div class="accordion-inner">
                    Sabia que você ia perguntar isso... É o que as pessoas mais perguntam! <a href="<?php echo $this->basePath()?>/crowdfundingxrecorrente">Preparamos um infográfico</a> que explica melhor!
                    </div>
                  </div>
              </div>

              <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse17">
                    Quando recebo minha recompensa?
                    </a>
                  </div>
                  <div id="collapse17" class="accordion-body collapse">
                    <div class="accordion-inner">
                    Toda vez que uma meta é batida, os assinantes recebem uma recompensa para marcar esse momento. Então, quanto mais gente você chamar pra participar da campanha, maiores são as chances dessa recompensa chegar mais rápido! #ficadica
                    </div>
                  </div>
              </div>

              <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse18">
                    Minha recompensa varia com o valor da minha assinatura?
                    </a>
                  </div>
                  <div id="collapse18" class="accordion-body collapse">
                    <div class="accordion-inner">
                    Nós sempre sugerimos aos responsáveis pelas campanhas que, independente do valor de contribuição, a recompensa seja coletiva e igual para todos os elos da corrente! Mais do que dar importância a cada um dos apoiadores individualmente, queremos celebrar o poder da rede - e a intenção é  expandir cada vez mais!
                    </div>
                  </div>
              </div>
                <hr>

                    <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse19">
                    Minha iniciativa se encaixa na plataforma?
                    </a>
                  </div>
                  <div id="collapse19" class="accordion-body collapse">
                    <div class="accordion-inner">
                    Olha, essa pode ser uma questão delicada! O Recorrente, assim como tudo que a Benfeitoria faz, é pensado para iniciativas de impacto positivo e interesse coletivo. Além disso, queremos contar com iniciativas coesas, que dêem força e credibilidade umas às outras, gerando uma rede resiliente de troca. Não aceitamos propostas puramente comerciais e tampouco campanhas político-partidárias ou de promoção religiosa.
                    </div>
                  </div>
              </div>
              
              <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse20">
                    Quanto posso arrecadar através da plataforma?
                    </a>
                  </div>
                  <div id="collapse20" class="accordion-body collapse">
                    <div class="accordion-inner">
                   O quanto a sua rede quiser contribuir! Não há limites! Mas não vá achando que é fácil, provavelmente você vai suar a camisa!
                    </div>
                  </div>
              </div>

              <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse21">
                    Como é feito repasse do dinheiro arrecadado?
                    </a>
                  </div>
                  <div id="collapse21" class="accordion-body collapse">
                    <div class="accordion-inner">
                   Através de uma conta Moip que você vai ter que fazer. Fica tranquilo, que a gente te orienta ;)
                    </div>
                  </div>
              </div>

              <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse22">
                    Tá. Mas o que é a Moip?
                    </a>
                  </div>
                  <div id="collapse22" class="accordion-body collapse">
                    <div class="accordion-inner">
                   A Moip é a operadora de pagamentos que faz o gerenciamento de todo o fluxo financeiro da plataforma. Todos os dados de pagamento são transmitidos para os servidores dela diretamente, com total segurança. A Moip faz o processamento do pagamento e cuida do dinheiro até o mesmo ser repassado para o responsável pela campanha, que então pode fazer uma transferência para o seu banco. Por tudo isso, ela cobra 5% sobre o valor mensal arrecadado.
                    </div>
                  </div>
              </div>

               <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse23">
                    Por quanto tempo minha campanha pode ficar na plataforma?
                    </a>
                  </div>
                  <div id="collapse23" class="accordion-body collapse">
                    <div class="accordion-inner">
                   Enquanto a plataforma existir, seu projeto pode estar aqui. E a gente espera que isso seja muuuuuito tempo!
                    </div>
                  </div>
              </div>

                <div class="accordion-group">
                  <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionFAQ" href="#collapse24">
                    Quanto custa para publicar uma campanha na plataforma?
                    </a>
                  </div>
                  <div id="collapse24" class="accordion-body collapse">
                    <div class="accordion-inner">
                  Publicar não custa nada, mas exige algum esforço. Depois de publicada a campanha, a gente cobra um valor de 8% sobre o valor arrecadado por mês. Afinal, a gente poderia estar **curtindo uma praia, vendendo hot dog ou passando trote**,  mas estamos aqui criando redes-ecossitêmicas-de-retroalimentação-potencial para iniciativas que valem a pena (ufa!). E não esqueça que também tem a taxa de 5% da Moip (operadora de pagamentos). Mas fique tranquilo, basta levar essas taxas em consideração quando for estipular suas metas de arrecadação que fica tudo resolvido.
                    </div>
                  </div>
              </div>


              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
