<?php echo $this->headTitle("Login | Recorrente: financiamento contínuo"); ?>

  <div class="section login">
    <div class="container">
      <div class="row">
        <div class="span12">
          <h2 class='lead'>Autenticação Necessária</h2>
          <!-- <p class='lead'>Para acessar esta área do nosso site, você precisa ter um cadastro junto a Benfeitoria.</p> -->
          <hr>
        </div>
      </div>

      <div class="row getdown">
        <div class="span6">
          <form action="<?php echo $this->basePath()?>/seguro/validaLogin" method="post">
<?php
    if (!empty($sURLRedirect)) { 
?>          
            <input type="hidden" name="url_redirect" value="<?php echo $sURLRedirect?>">
<?php
    } 
?>
<h3>Já tenho cadastro</h3> <br> <br>
<?php
    if (!empty($sMessage)) { 
?>          
           <p class="text-error" style="width:395px"><?php echo $sMessage?></p>
<?php
    } 
?>
            <label>
              <input type="text" id='login_mail' placeholder='Informe seu email' name="usuario">
            </label>
            <label>
              <input type="password"  id='login_senha' placeholder='Senha' name="senha">
            </label>
            <a href="<?php echo $this->basePath()?>/seguro/recuperarSenha">Esqueci minha senha</a>
             <input class="btn btn-primary" type="submit" name="#" value="Entrar" />
          </form>
        </div>

        <div class="span6">
          <div class="semcadastro">
          <h3>Não tenho cadastro ainda</h3><br>
          <em>Escolha qual o tipo de seu perfil: </em> <br>
          <br>
           <a href="<?php echo $this->basePath()?>/cadastroPJ"><button class="btn btn-primary">Pessoa Jurídica</button></a>
           <br> <br>
           <a href="<?php echo $this->basePath()?>/cadastroPF"><button class="btn btn-primary">Pessoa Física</button></a>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>

    <div id="push"></div>