<?php echo $this->headTitle("Termos de Uso | Recorrente: financiamento contínuo"); ?>

      <div class="section generic">
      <div class="wide-bg" >
        <div class="container">
          <div class="row">
            <!-- Aqui vai o contéudo -->
            <div class="span12 faqPage">
              <div class="pagePadrao">
                <h2>Termos de Uso</h2>
                <br>
            A LEITURA ATENTA E POSTERIOR ACEITAÇÃO DO TERMO DE USO SÃO ABSOLUTAMENTE INDISPENSÁVEIS À UTILIZAÇÃO DOS SERVIÇOS OFERECIDOS POR BENFEITORIA MIRABOLANTE - SERVIÇOS CRIATIVOS NA INTERNET LTDA., SOCIEDADE LIMITADA, INSCRITA NO CNPJ SOB Nº 12.909.805./0001-31, DORAVANTE DENOMINADA “BENFEITORIA”, POR MEIO DA PLATAFORMA DENOMINADA "RECORRENTE", HOSPEDADA EM SEU WEBSITE recorrente.benfeitoria.com.<br/>
ESTE CONTRATO APLICA-SE A QUALQUER PESSOA, DORAVANTE NOMINADA “USUÁRIO”, QUE UTILIZE O WEBSITE OU SERVIÇOS OFERECIDOS, INCLUSIVE OS QUE TAMBÉM CONTRIBUEM COM CONTEÚDOS, INFORMAÇÃO, E OUTROS MATERIAIS OU SERVIÇOS NO WEBSITE.<br/>
<br/>
Caso os haja alguma dúvida sobre as condições estabelecidas neste termo ou qualquer documento do website, por favor envie um e-mail para contato@benfeitoria.com. Será um prazer ajudar a esclarecer qualquer de suas dúvidas.<br/>
 <br/>
1. ACEITAÇÃO DO TERMO<br/>
 <br/>
1.1. Ao usar o RECORRENTE de qualquer forma, incluindo, mas não se limitando a visitar ou navegar no website e publicar ou colaborar com campanhas, você concorda com estes Termos de Uso, que incluem a Política de Privacidade, bem como com as regras operacionais e procedimentos que possam ser publicados no website de tempos em tempos.<br/>
 <br/>
1.2. Os serviços do RECORRENTE estão disponíveis apenas para as pessoas que tenham capacidade legal para contratá-los. Não podem utilizá-los, assim, menores de 18 (dezoito) anos, ou quaisquer pessoas que não possuam capacidade civil plena.<br/>
 <br/>
 <br/>
 <br/>
2. PROPÓSITO DO RECORRENTE<br/>
2.1 Objetivos e ferramentas<br/>
2.1.1 O objetivo da plataforma RECORRENTE, por meio de seu website, consiste em colocar à disposição dos Usuários um espaço para que se promova iniciativas de qualquer tema ou abrangência, que provoquem algum tipo de impacto positivo e tenham a necessidade de arrecadação financeira mensal para suas atividades. O RECORRENTE facilita, portanto, que os Usuários tomem conhecimento uns dos outros, servindo como um ponto de encontro entre pessoas que precisam de recursos para viabilizar suas iniciativas, doravante denominados “Realizadores”, e pessoas que têm interesse em colaborar para o financiamento, doravante denominados “Colaboradores”.<br/>
 <br/>
2.1.2 Como meio de realizar seu objetivo, o RECORRENTE oferece ferramentas que facilitam que os Realizadores tenham suas iniciativas viabilizadas através da arrecadação de recursos financeiros oferecidos pelos Colaboradores em forma de assinatura mensal.<br/>
 <br/>
3. COMO FUNCIONA: REGRAS BÁSICAS<br/>
<br/>
3.1 Envio de proposta e publicação de uma campanha<br/>
3.1.1 A publicação de uma campanha no RECORRENTE é e deve ser feita através dos passos descritos no item 4.1, quando os Realizadores devem responder um formulário no qual será possível descrever a iniciativa e fazer a proposta de campanha.<br/>
 <br/>
3.1.2 A equipe do RECORRENTE vai analisar a proposta e entrar em contato em até 05 (cinco) dias úteis para tirar eventuais dúvidas ou fazer quaisquer questionamentos. Algumas vezes será necessário fazer ajustes na proposta inicial para que ela se adeque ao propósito da plataforma. Outras vezes, a proposta não se encaixará na filosofia da plataforma e equipe do RECORRENTE terá autonomia para recusar tais propostas.<br/>
<br/>
3.1.3 Se aprovada a proposta, começa a fase de desenvolvimento dos materiais que farão parte da página da campanha publicada, que incluem:<br/>
Vídeo de apresentação<br/>
Texto descritivo<br/>
03 (três) metas iniciais<br/>
Foto de capa e outras imagens<br/>
<br/>
3.1.4 Uma vez que todos os materiais estejam terminados e forem aprovados pela equipe do RECORRENTE, acontece a publicação e a campanha ganha uma página própria na plataforma, através da qual os Colaboradores poderão contribuir com as assinaturas mensais de valores a partir de R$10.<br/>
 <br/>
3.1.6 A responsabilidade sobre a divulgação e captação de recursos dos Colaboradores é exclusivamente do Realizador, sendo a equipe do RECORRENTE apenas uma facilitadora desse processo, de modo que não lhe imputável qualquer responsabilidade sobre o sucesso da arrecadação.<br/>
 <br/>
3.2 Colaboração e pagamento<br/>
3.2.1 Para colaborar com uma campanha, o Usuário deverá (i) entrar na página da campanha em questão; (ii) clicar no botão de chamada para apoio; (iii) entrar seus dados de login ou preencher o formulário de cadastro (iv) ler e aceitar os Termos de Uso do RECORRENTE; (v) colocar seus dados de pagamento, que serão passados diretamente para a operadora Moip, conforme descrito no item 5.1.<br/><br/>
<br/>
3.2.2 Toda colaboração feita para uma campanha na plataforma RECORRENTE é uma assinatura mensal. Ao fazer uma colaboração, o Colaborador se informa ciente de que aquele mesmo valor será descontado de seu cartão de crédito em todos os meses, até que seja feito o cancelamento da assinatura pelo próprio colaborador ou por algum outro motivo externo, como falta de pagamento, por exemplo.<br/>
<br/>
3.2.3 O primeiro pagamento é feito na hora da colaboração e a partir daí todos os pagamentos são descontados nos dias 10 ou 25 de cada mês.<br/>
<br/>
3.2.4 A partir do primeiro pagamento, o Colaborador entra para a lista de Assinantes da campanha. Caso a assinatura seja cancelada por qualquer motivo, o Usuário deixa de fazer parte da lista de Assinantes.<br/>
<br/>
3.2.5 O Colaborador pode modificar o valor de sua assinatura ou cancelá-la a qualquer momento que julgar conveniente.<br/>
 <br/>
3.2.6 O Realizador terá acesso a lista completa das colaborações e seus respectivos colaboradores, incluindo seus dados cadastrais.<br/>
<br/>
3.2.7 Todas as transações são gerenciadas pelo serviço de pagamento Moip (“money over IP” – www.moip.com.br), inclusive a parte de segurança dos dados. A comunicação entre os servidores do RECORRENTE e da Moip usa a ferramenta conhecida como Checkout Transparente Moip, que faz com que os dados dos Usuários nunca passem pelos servidores do RECORRENTE, como melhor explicado no item 5.1.<br/>
 <br/>
 <br/>
3.3 Metas e Recompensas<br/>
3.3.1 O sistema de arrecadação de recursos de forma contínua oferecido pelo RECORRENTE estabelece que metas devem ser designadas pelos Realizadores como forma de comunicar a todos os Usuários o destino dos recursos, bem como motivar a colaboração e criar marcos significativos ao longo do processo.<br/>
<br/> 
3.3.2. As metas são valores financeiros mensais que a campanha deseja alcançar para fins específicos. Quando a meta atual é ultrapassada, o sistema automaticamente coloca aquela meta como concluída e atualiza para que a próxima meta seja usada como meta atual. Cada meta é composta por 03 (três) componentes básicos:<br/>
Valor financeiro: o valor mensal de arrecadação que se deseja atingir;<br/>
Proposta de entrega: o que será feito com o dinheiro caso aquele valor seja arrecadado mensalmente;<br/>
Proposta de recompensa: uma recompensa para os apoiadores a ser entregue caso a campanha atinja a meta (melhor explicado no item 3.2.2)<br/>
<br/>
<br/>
 <br/>
3.3.3. As recompensas são sempre atreladas a metas e são baseadas no conceito de celebração. Diferentemente das plataformas de crowdfunding com colaborações pontuais, nas quais para cada colaboração é entregue uma recompensa, no RECORRENTE as recompensas são entregues sempre que uma meta é batida, como forma de marcar este momento importante.<br/>
<br/>
3.3.4 As recompensas poderão ser produtos, serviços, experiências (participação em cursos, festas, workshops etc) ou até mesmo simbólicas (agradecimento, reconhecimento, nome nos créditos etc).<br/>
<br/>
3.3.5 Não é permitido que se ofereça recompensas financeiras como incentivo a colaborações, incluindo, mas não se limitando a: oferta de participação societária em entes com fins lucrativos ou de qualquer espécie de valor mobiliário, bem como a promoção de rifas e sorteios. Fica claro aos Colaboradores, portanto, que contribuições financeiras não poderão ser realizadas objetivando retorno financeiro.<br/>
<br/>
3.4 Benefícios<br/>
3.4.1 As iniciativas são encorajadas a oferecer benefícios aos seus colaboradores, como o direito de voto em alguma questão específica, o acesso a informações internas ou a participação em algum tipo de evento, por exemplo. Esta é uma forma de incentivar as colaborações dando protagonismo ao colaborador dentro da iniciativa, transformando-o em um agente ativo dentro do processo.<br/>
<br/>
Esses benefícios nada têm a ver com as recompensas, explicadas no item 3.2, que marcam a conquista de uma meta financeira específica.<br/>
 <br/>
<br/>
3.5 O Papel da Benfeitoria e a Responsabilidade Exclusiva do Realizador pela Implementação<br/>
 <br/>
3.5.1 A plataforma RECORRENTE apenas oferece a estrutura de seu website e não participa da idealização das iniciativas nele veiculados, nem de sua implementação. As campanhas veiculadas, a execução dos objetivos e a entrega das recompensas prometidas são de responsabilidade exclusiva dos Realizadores. A Benfeitoria não se responsabiliza, portanto, pelo modo de utilização dos recursos, pela efetivação dos objetivos e pela entrega de tais recompensas, por sua veracidade ou por sua qualidade.<br/>
 <br/>
3.5.2. Eventualmente a Benfeitoria poderá publicar uma campanha própria. Nesse caso, a referida informação será veiculada expressamente em seu website e, única e exclusivamente nessa hipótese, assumirá as responsabilidades próprias de um Realizador.<br/>
 <br/>
 <br/>
 <br/>
3.6 Possibilidade de pós-moderação<br/>
3.6.1 O relacionamento entre os Realizadores e os Colaboradores ocorre de forma direta, sem intervenção da Benfeitoria, que apenas disponibiliza o espaço em seu website. A Benfeitoria não faz intermediação de negócios por meio da plataforma RECORRENTE. A Benfeitoria, muito embora não assuma a responsabilidade pelo conteúdo gerado por seus Usuários, nem possua qualquer obrigação de monitorar seu conteúdo, se reserva o direito de discricionariamente e a seu exclusivo critério retirar do website quaisquer conteúdos considerados impróprios.<br/>
  <br/>
3.7 A filosofia da plataforma<br/>
3.7.1 O RECORRENTE, assim como a Benfeitoria, existe para ajudar a dar vida a iniciativas que gerem impacto coletivo. Para uma campanha ser aceita na plataforma, ela deve articular qual é o tipo de impacto que gera e como os recursos mobilizados através do RECORRENTE ajudarão a expandir este impacto. Todas as propostas passarão pela análise da equipe do RECORRENTE, que verificará se as mesmas estão alinhadas com a filosofia da plataforma e da Benfeitoria. Apenas campanhas com esse alinhamento conceitual serão publicadas.<br/>
<br/>
3.7.2 Não são permitidas e poderão ser retiradas do ar quaisquer campanhas com conteúdo ilegal, imoral, obsceno, racista, ofensivo ou esteja em desacordo com a moral e os bons costumes ou com a legislação vigente, ou que descumpra qualquer condição estabelecida nesse Termo. Também não serão aceitas campanhas político-partidárias ou com tema de promoção religiosa.<br/>
 <br/>
4. AS CAMPANHAS: DETALHES<br/>
<br/>
4.1 Publicação da campanha<br/>
4.1.1 Para publicar uma iniciativa no website e se tornar um Realizador, o Usuário deverá clicar no link de envio de proposta e passar pelas seguintes etapas: (i) cadastro completo; (ii) leitura na íntegra e com atenção deste Termos de Uso, Política de Privacidade e demais regras de utilização do RECORRENTE; (iii) leitura atenta da apresentação que mostra os detalhes sobre a dinâmica; (iv) descrição da iniciativa por meio de preenchimento do formulário online; (v) detalhamento das 03 (três) primeiras metas e suas recompensas associadas; (vi) submissão da proposta para conferência dos dados e publicação pelo administrador da plataforma.<br/>
 <br/>
4.1.2 Caso a proposta esteja de acordo com as condições estabelecidas nesse termo, após o processo descrito no item 3.1 e seus subitens, o Realizador receberá uma página da campanha na plataforma, que ficará disponível online para receber contribuições dos Colaboradores através do endereço recorrente.benfeitoria.com/xyz - sendo “xyz” o nome selecionado pelo Realizador no momento de cadastro.<br/>
 <br/>
4.1.2. Campanhas que não estejam de acordo com as condições estabelecidas nesse termo não serão publicadas. A equipe do RECORRENTE informará ao Realizador o motivo da sua não publicação e, eventualmente, os ajustes necessários para que possa ser publicada.<br/>
 <br/>
 <br/>
4.2 Filtros e Seleção Vitrine<br/>
4.2.1 Nem todas as campanhas publicadas estarão expostas na página principal (vitrine) do website. A equipe do RECORRENTE selecionará, a seu exclusivo critério, as campanhas que figurarão em sua vitrine. O Usuário poderá, todavia, escolher a exibição de campanhas durante sua navegação, na página de listagem de campanhas , inclusive selecionando filtros adicionais e temas, ou ainda fazer uma busca por palavra-chave.<br/>
 <br/>
 <br/>
4.3 Acompanhamento da Campanha por parte do Realizador<br/>
4.3.1 Uma vez que a campanha tenha sido publicada, o Realizador terá acesso a uma área exclusiva de controle, onde poderá acessar a qualquer momento o status de sua campanha, atualizar as áreas de novidades e prestação de contas.<br/>
<br/>
4.3.2 Uma vez por mês, ao ser feita a transferência dos valores arrecadados, o Realizador receberá um relatório das contribuições recebidas naquele mês, com nome e e-mail de cada colaborador, além do valor colabora.<br/>
<br/>
4.4 Transparência e prestação de contas<br/>
<br/>
4.4.1 A transparência é um dos pilares fundamentais da existência do RECORRENTE. Todas as iniciativas devem fazer um esforço extra neste sentido.<br/> 
<br/>
4.4.2 Haverá em cada página de campanha um acompanhamento em tempo real para que os Usuários saibam quanto dinheiro está sendo arrecadado mensalmente, proveniente de quantos Usuários, quais metas já foram batidas e quanto falta para ultrapassar a próxima meta.<br/>
<br/>
4.4.3 Os Realizadores devem atualizar pelo menos uma vez por mês a aba Prestação de Contas na página da campanha, com informações do andamento dos trabalhos e dados sobre como estão sendo empregados os recursos<br/>
<br/>
 <br/>
4.5 Isenção de responsabilidade sobre tributos relacionados às atividades dos Usuários<br/>
 <br/>
4.5.1 A Benfeitoria recomenda aos Usuários que se informem acerca de eventuais tributos incidentes sobre a entrega e/ou o recebimento de recursos realizados por meio do website. A Benfeitoria não se responsabiliza pelas obrigações tributárias que recaiam sobre as atividades dos Usuários do website, que são de responsabilidade única e exclusiva dos Usuários.<br/>
<br/>
 <br/>
4.6 Atualização de informações da campanha<br/>
 <br/>
4.6.1 Os Realizadores se comprometem a atualizar periodicamente sua área de novidades e a responder comentários dos Usuários na página da campanha, assim como atualizar a área de prestação de contas pelo menos uma vez por mês. Estas atualizações são muito importantes para que os Colaboradores possam ter informações sobre os benefícios gerados por suas contribuições. Caso referida página não seja atualizada de forma satisfatória, o Realizador será notificado, podendo ter sua campanha retirada do ar.<br/>
 <br/>
 <br/>
 <br/>
5. SISTEMA DE PAGAMENTOS<br/>
 <br/>
5.1 Contribuição através da Moip<br/>
5.1.1 A colaboração com recursos financeiros será feita por meio do sistema Moip (“money over IP” – www.moip.com.br). O sistema Moip permite ao RECORRENTE exibir o status de arrecadação em tempo real na página da campanha, e cobra uma comissão sobre as contribuições feitas, melhor explicada no item 6.2<br/>
<br/>
5.1.2 O RECORRENTE se comunica com a operadora Moip através da ferramenta conhecida como Checkout Transparente Moip, que faz com que os dados de pagamento nunca passem pelos servidores administrados pela Benfeitoria. Todos os dados são repassados diretamente à Moip de forma segura.<br/>
<br/>
5.2 Pagamentos mensais<br/>
5.2.1 O RECORRENTE utiliza o serviço Moip Assinaturas para gerar pagamentos mensais para as campanhas. Toda colaboração na plataforma é considerada uma assinatura mensal e será descontada todo mês até que a assinatura seja cancelada pelo Colaborador.<br/>
<br/>
5.3 Recebimento do dinheiro<br/>
5.3.1 O valor total das contribuições mensais, deduzido as comissões (item 6), será transferido para uma conta do Realizador na Moip, até o dia 05 do mês seguinte à arrecadação. O valor poderá ser integralmente sacado a qualquer momento seguindo as regras da Moip (na última atualização deste termo: saque gratuito para valores acima de R$ 250 e mediante a pagamento de R$ 2 para bancos conveniados e R$ 8 para bancos não-conveniados, se o valor de saque for inferior a R$ 250). Em qualquer caso, a forma e prazo de reembolso são estipulados pela Moip, de acordo com suas regras de funcionamento, sobre as quais a Benfeitoria não possui qualquer ingerência.<br/>
<br/>
5.4 Isenção de responsabilidade da Benfeitoria – Serviços Oferecidos pelo Moip<br/>
5.4.1 A Benfeitoria não possui controle sobre o serviço de pagamento online fornecido pelo Moip, inclusive sobre os referidos nessa Cláusula 5, bem como pelos sistemas de cartão de crédito e débito, de modo que não se responsabiliza, nem garante de qualquer forma, os pagamentos processados por meio do Moip, ou com uso de cartões de crédito e débito.<br/>
<br/>
5.4.2 A Benfeitoria não poderá intervir nos resultados da relação do Usuário com a empresa responsável por gestão de pagamentos, uma vez que a mesma administra suas operações independentemente da Benfeitoria.<br/>
 <br/>
5.4.3 A Benfeitoria não pode garantir de forma nenhuma que os serviços prestados pela empresa responsável pela gestão de pagamentos funcionarão livres de erros, interrupções, mau funcionamento, atrasos ou outras imperfeições.<br/>
 <br/>
5.4.4 A Benfeitoria não será responsável pela disponibilidade ou não dos serviços prestados pela empresa responsável pela gestão de pagamentos ou pela impossibilidade do uso do serviço.<br/>
<br/>
5.4.5 Caso um pagamento não seja computado por qualquer motivo, como cancelamento do cartão de crédito ou vencimento de sua validade, o Colaborador será notificado e, caso não forneça novos dados válidos para pagamento, sua assinatura será cancelada e ele será excluído da lista de Assinantes da campanha no mês seguinte.<br/>
 <br/>
 <br/>
6. COMISSÕES<br/>
 <br/>
A comissão da Benfeitoria pelo serviço da plataforma RECORRENTE<br/>
 <br/>
6.1. A Benfeitoria cobra 8% de comissão sobre todas as contribuições à campanhas dentro da plataforma RECORRENTE.<br/>
 <br/>
 <br/>
Comissão do Sistema de Pagamentos – Moip<br/>
 <br/>
6.2. A comissão cobrada pela Moip para todas as contribuições feitas usando cartão de crédito é de R$0,39 + 4,9% dos pagamentos feitos com cartão de crédito ou débito, até a última atualização destes termos. Esses percentuais poderão ser alterados de tempos em tempos, de acordo com as regras do Moip.<br/>
 <br/>
 <br/>
7. PATROCINADORES<br/>
 <br/>
 <br/>
 <br/>
Autorização para Veiculação de Marcas<br/>
 <br/>
7.1. O Realizador, ao utilizar a plataforma RECORRENTE, aceita e reconhece o direito da Benfeitoria e de seus eventuais patrocinadores veicularem suas marcas na área de “assinantes da campanha”, bem como nos materiais enviados para a plataforma como vídeo, imagem, texto ou apresentação.<br/>
 <br/>
 <br/>
Contribuição de Empresas para campanhas<br/>
 <br/>
7.2. A plataforma permite a contribuição de empresas para campanhas. Assim como qualquer Colaborador, a imagem dessas empresas poderá ser veiculada na aba de Assinantes.<br/>
 <br/>
 <br/>
Iniciativas que já Possuem Patrocinadores<br/>
 <br/>
7.3. Caso a iniciativa coordenadora da campanha já possua alguma empresa patrocinadora ou apoiadora, o Realizador poderá utilizar a área de descrição da campanha para veicular a respectiva imagem da pessoa jurídica em questão, desde que previamente submetido e aprovado pela Benfeitoria, cabendo ao Realizador toda a responsabilidade sobre o uso dessas respectivas imagens. As imagens de tais empresas somente serão veiculadas na área de Assinantes do projeto se houver alguma colaboração da empresa com a campanha através da plataforma.<br/>
 <br/>
 <br/>
8. CADASTRO<br/>
 <br/>
Informações Cadastrais<br/>
 <br/>
8.1. O cadastramento do interessado será confirmado apenas quando preencher todos os campos obrigatórios do cadastro. O Usuário deverá completá-lo com informações exatas, precisas e verdadeiras, e assume o compromisso de atualizar seus dados pessoais sempre que neles ocorrer alguma alteração.<br/>
<br/>
8.1.2 O Usuário deve fornecer um e-mail válido ao se cadastrar e deve confirmar o e-mail através dos procedimentos descritos em uma mensagem que será enviada ao endereço fornecido logo após o cadastro. Apenas após essa confirmação, o cadastro se tornará válido.<br/>
 <br/>
 <br/>
Responsabilidade do Usuário sobre informações cadastrais<br/>
 <br/>
8.2. A Benfeitoria não se responsabiliza pela correção dos dados pessoais inseridos por seus Usuários. Os Usuários garantem e respondem, em qualquer caso, pela veracidade, exatidão e autenticidade dos dados pessoais cadastrados.<br/>
 <br/>
 <br/>
Identificação do Usuário<br/>
 <br/>
8.3. Sem prejuízo das cláusulas acima, a Benfeitoria se reserva o direito de utilizar todos os meios válidos e possíveis para identificar seus Usuários, bem como de solicitar dados adicionais e documentos que estime serem pertinentes a fim de conferir os dados pessoais informados.<br/>
 <br/>
 <br/>
Cancelamento de Usuário por dados incorretos<br/>
 <br/>
8.4. Caso a Benfeitoria decida checar a veracidade dos dados cadastrais de um Usuário e se constate haver entre eles dados incorretos ou inverídicos, ou ainda caso o Usuário tenha agido de má-fé, se furte ou negue a enviar os documentos requeridos, a Benfeitoria poderá bloqueá-lo para a publicação de campanhas, ou ainda suspender temporariamente ou cancelar definitivamente o cadastro do Usuário, sem prejuízo de outras medidas que entender necessárias e oportunas.<br/>
 <br/>
8.5. Havendo a aplicação de qualquer das sanções acima referidas, automaticamente serão canceladas as publicações de campanhas feitas pelo Usuário no website, não assistindo ao Usuário, por essa razão, qualquer sorte de indenização ou ressarcimento.<br/>
 <br/>
 <br/>
Privacidade e senha de acesso<br/>
 <br/>
8.6. O Usuário acessará sua conta através de e-mail e senha e compromete-se a não informar a terceiros esses dados, responsabilizando-se integralmente pelo uso que deles seja feito.<br/>
 <br/>
 <br/>
Uso não Autorizado – Responsabilidade do Usuário por sua senha<br/>
 <br/>
8.7. O Usuário compromete-se a notificar a Benfeitoria imediatamente, e através de meio seguro, a respeito de qualquer uso não autorizado de sua conta, bem como seu acesso não autorizado por terceiros. O Usuário será o único responsável pelas operações efetuadas em sua conta.<br/>
 <br/>
 <br/>
Intransferibilidade de contas<br/>
 <br/>
8.8. Em nenhuma hipótese será permitida a cessão, venda, aluguel ou outra forma de transferência da conta ou de titularidade de projeto. Também não se permitirá a manutenção de mais de um cadastro por uma mesma pessoa, ou ainda a criação de novos cadastros por pessoas cujos cadastros originais tenham sido cancelados por infrações às políticas da Benfeitoria.<br/>
 <br/>
 <br/>
Publicação de conteúdo inadequado<br/>
 <br/>
8.9. No ato de cadastro as pessoas que se cadastrarem deverão fornecer seu CPF ou CNPJ, conforme o caso.  A Benfeitoria se reserva o direito de discricionariamente bloquear o acesso aos serviços e ferramentas do website por CPF ou CNPJ de Usuários que publiquem conteúdo que a Benfeitoria considere inadequado aos objetivos do website.<br/>
 <br/>
 <br/>
9. MODIFICAÇÕES DO TERMO DE USO<br/>
 <br/>
 <br/>
9.1. A Benfeitoria poderá alterar, a qualquer tempo, este Termo de Uso, visando seu aprimoramento e melhoria dos serviços prestados. O novo Termo de Uso entrará em vigor a partir de sua publicação no website. No prazo de 24 (vinte e quatro) horas contado a partir da publicação das modificações, o Usuário deverá comunicar-se por e-mail, caso não concorde com o Termo de Uso alterado. Nesse caso, o vínculo contratual deixará de existir, desde que não haja pendências em aberto em nome do Usuário. Não havendo manifestação no prazo estipulado, entender-se-á que o Usuário aceitou tacitamente o novo Termo de Uso e o contrato continuará vinculando as partes.<br/>
 <br/>
9.2 As alterações não vigorarão em relação a campanhas já publicadas e Contribuições já efetuadas antes das alterações nos Termos de Uso entrarem em vigor. Nesses casos, o Termo de Uso valerá com a redação vigente no momento da publicação da campanha.<br/> 
 <br/>
 <br/>
10. PRIVACIDADE DA INFORMAÇÃO<br/>
 <br/>
 <br/>
10.1. A Benfeitoria tomará todas as medidas possíveis para manter a confidencialidade e a segurança das informações fornecidas pelos Usuários que tenham caráter sigiloso, nos termos da Política de Privacidade, cuja aceitação é requisito necessário à utilização do website. A Benfeitoria não responderá, entretanto, por prejuízo que possa ser derivado da violação dessas medidas por parte de terceiros que, utilizando as redes públicas ou a internet, subvertam os sistemas de segurança para acessar as informações de Usuários.<br/>
<br/>
10.2 Nenhuma informação relacionada aos dados de pagamento circulará pelos servidores administrados pela Benfeitoria. Estes dados são repassados diretamente à operadora Moip utilizando a ferramenta conhecida como Checkout Transparente Moip<br/>
 <br/>
 <br/>
11. VIOLAÇÃO NO SISTEMA OU BASE DE DADOS.<br/>
 <br/>
 <br/>
11.1. Não é permitido a utilização de nenhum dispositivo, software, ou outro recurso que venha a interferir nas atividades e operações da Benfeitoria, bem como nas publicações de campanhas, descrições, contas ou seus bancos de dados. Qualquer intromissão, tentativa de, ou atividade que viole ou contrarie as leis de direito de propriedade intelectual e/ou as proibições estipuladas nestes Termos de Uso, tornarão o responsável passível das ações legais pertinentes, bem como das sanções aqui previstas, sendo ainda responsável pelas indenizações por eventuais danos causados.<br/>
 <br/>
 <br/>
12. SANÇÕES<br/>
 <br/>
 <br/>
12.1 Sem prejuízo de outras medidas, a Benfeitoria poderá advertir, suspender ou cancelar, temporária ou definitivamente, a conta de um Usuário a qualquer tempo, e iniciar as ações legais cabíveis se: a) o Usuário não cumprir qualquer dispositivo destes Termos de Uso; b) se praticar atos fraudulentos, dolosos, ilegais ou ainda considerados imorais pela Benfeitoria; c) se não puder ser verificada a identidade do Usuário ou qualquer informação fornecida por ele esteja incorreta; d) se a Benfeitoria entender que qualquer atitude do Usuário tenha causado algum dano a terceiros ou à própria Benfeitoria ou tenham a potencialidade de assim o fazer. Nos casos de inabilitação do cadastro do Usuário, todos os projetos ativos ou não serão automaticamente cancelados e excluídos da plataforma. A Benfeitoria reserva-se o direito de, a qualquer momento e a seu exclusivo critério, solicitar o envio de documentação pessoal.<br/>
 <br/>
<br/> 
13. RESPONSABILIDADES.<br/>
<br/> 
13.1 Idealização e execução<br/>
13.1.1 Conforme referido nestes Termos de Uso, a Benfeitoria não possui responsabilidade sobre a idealização e execução dos conteúdos de campanhas publicadas, pela veracidade dos dados fornecidos pelos Usuários cadastrados, nem pelas recompensas oferecidas pelos Realizadores.<br/>
<br/> 
13.2 Relação Colaborador-Realizador<br/>
13.2.1 O COLABORADOR RECONHECE E ACEITA QUE AO CONTRIBUIR PARA UMA CAMPANHA PUBLICADO POR UM Realizador, O FAZ POR SUA CONTA E RISCO. A Benfeitoria não será responsável pelo efetivo cumprimento das obrigações assumidas pelos Usuários, nem por qualquer outro dano e/ou prejuízo, material ou moral, que o Usuário possa sofrer devido às contribuições realizadas através da plataforma RECORRENTE.<br/>
 <br/>
 <br/>
13.3 Isenção de responsabilidade da Benfeitoria por problemas no sistema<br/>
13.3. Tendo em vista, ainda, a impossibilidade de funcionamento integral e ininterrupto de qualquer sistema de telecomunicação ou de informática, durante 365 dias por ano, 24 horas por dia, nesta situação de fragilidade também se incluindo, em razão de sua complexidade, a disponibilização dos serviços objeto destes Termos de Uso, inclusive em razão da dependência de serviços de telecomunicações prestados por terceiros, a Benfeitoria não garante, de nenhuma forma, a prestação do serviço RECORRENTE de forma ininterrupta e/ou isenta de erros.<br/>
 <br/>
 <br/>
13.4 Benfeitoria apenas disponibiliza plataforma virtual – ausência de responsabilidade<br/>
 <br/>
13.4.1. Estes Termos de Uso não geram nenhum contrato de sociedade, de mandato, franquia ou relação de trabalho entre a Benfeitoria e o Usuário.<br/>
 <br/>
13.4.2. O Usuário manifesta ciência de que a Benfeitoria não é parte de nenhuma transação, nem possui controle algum sobre a qualidade e a segurança das recompensas oferecidas pelos Realizadores, bem como pela efetiva realização dos objetivos anunciados.<br/>
 <br/>
13.4.3. A Benfeitoria não garante a veracidade da publicação de terceiros que apareça no website RECORRENTE e não será responsável pela correspondência ou contratos que o Usuário realize com terceiros.<br/>
 <br/>
13.4.4. A Benfeitoria não se responsabiliza por qualquer dano, prejuízo ou perda no equipamento do Usuário causado por falhas no sistema, no servidor ou na internet decorrentes de condutas de terceiros.<br/>
 <br/>
13.4.5. A Benfeitoria também não será responsável por qualquer vírus que possa atacar o equipamento do Usuário em decorrência do acesso, utilização ou navegação no website na internet; ou como consequência da transferência de dados, arquivos, imagens, textos ou áudio.<br/>
 <br/>
13.4.6. Os Usuários não poderão atribuir à Benfeitoria nenhuma responsabilidade nem exigir o pagamento por lucro cessante em virtude de prejuízos resultantes de dificuldades técnicas ou falhas nos sistemas ou na internet. Eventualmente, o sistema RECORRENTE poderá não estar disponível por motivos técnicos ou falhas da internet, ou por qualquer outro evento fortuito ou de força maior alheio ao controle da Benfeitoria.<br/>
 <br/>
 <br/>
13.5 Isenção de responsabilidade sobre links<br/>
 <br/>
13.5.1 O website pode conter links que dão acesso a outros websites da rede, o que não significa que esses websites sejam de propriedade ou operados pela Benfeitoria. Não possuindo controle sobre esses websites, a Benfeitoria não será responsável pelos conteúdos, práticas e serviços ofertados nos mesmos. A presença de links para outros websites não implica relação de sociedade, de supervisão, de cumplicidade ou solidariedade da Benfeitoria para com esses websites e seus conteúdos.<br/>
 <br/>
 <br/>
14. PROPRIEDADE INTELECTUAL<br/>
<br/>
14.1 Direito exclusivo de uso do nome empresarial, da marca e do domínio<br/>
 <br/>
14.1.1 O uso comercial da expressão "RECORRENTE" como marca, nome empresarial ou nome de domínio, bem como os conteúdos das telas relativas aos serviços do RECORRENTE assim como os programas, bancos de dados, redes e arquivos, que permitem que o Usuário acesse e use sua conta, são propriedade da Benfeitoria e estão protegidos pelas leis e tratados internacionais de direito empresarial, de direito autoral, marcas, patentes, modelos e desenhos industriais. O uso indevido e a reprodução total ou parcial dos referidos conteúdos são proibidos, salvo a autorização expressa da Benfeitoria.<br/>
 <br/>
14.2 Creative Commons<br/>
 <br/>
14.2.1 O uso de conteúdo público do RECORRENTE, bem como sobre as campanhas nele publicadas, será permitido através da licença de creative commons condicionado, cumulativamente, a (i) a atribuição de créditos à Benfeitoria; (ii) uso com fins não comerciais; e (iii) que a mesma licença será utilizada para os materiais compartilhados.<br/>
 <br/>
 <br/>
14.3 Permissão para Edição de Material enviado ao website pelos Usuários e Veiculação de Patrocínio<br/>
 <br/>
14.3.1 Os Usuários do RECORRENTE desde já autorizam a utilização e edição pela Benfeitoria de todo e qualquer material por eles enviado ao website, sem necessidade que qualquer outra permissão específica, bem como a veicular marcas dos patrocinadores nos vídeos e fotos dos projetos publicados no website.<br/>
 <br/>
 <br/>
Vedações ao Usuário<br/>
 <br/>
14.4. O Usuário não deverá fazer upload, download, postar, enviar, distribuir ou facilitar a distribuição de qualquer conteúdo através do website RECORRENTE que: (i) viole qualquer direito industrial ou intelectual de terceiros; (ii) saiba ser falso, enganoso ou inexato; (iii) seja é ilegal, ameaçador, abusivo, ofensivo, difamatório, fraudulento, invasivo da privacidade de outrem, injurioso, obsceno, ofensivo, ou; (iv) constitua publicidade não autorizada, ou spam; (v) contenha vírus de software ou qualquer outros códigos de computador, arquivos ou programas que são concebidos ou destinados a corromper, estragar, limitar ou interferir com o bom funcionamento de qualquer software, hardware ou equipamento de telecomunicações ou causar danos ou obter acesso a qualquer sistema, dados, senhas ou outras informações da Benfeitoria ou de terceiros; (v) que viole de qualquer forma não especificada acima direitos de terceiros.<br/>
 <br/>
 <br/>
15. Indenização<br/>
15.1. O Usuário indenizará a Benfeitoria, seus sócios, administradores, colaboradores, representantes e empregados por qualquer demanda promovida por outros Usuários ou terceiros decorrentes de suas atividades no website ou por seu descumprimento dos Termos de Uso ou pela violação de qualquer lei ou direitos de terceiros, incluindo honorários de advogados.<br/>
 <br/>
 <br/>
16. FORO E LEGISLAÇÃO APLICÁVEL.<br/>
 <br/>
16.1 Todos os itens deste Termo de Uso estão regidos pelas leis vigentes na República Federativa do Brasil. Para todos os assuntos referentes à sua interpretação e cumprimento, as partes se submeterão ao Foro Central da Comarca da Capital do Estado do Rio de Janeiro.<br/> 
 <br/>
================================================<br/>
 <br/>
POLÍTICA DE PRIVACIDADE DO RECORRENTE<br/>
 <br/>
A Política de Privacidade tem como objetivo deixar claro o compromisso da Benfeitoria de não divulgar os dados dos usuários de seu website RECORRENTE a terceiros, salvo nas situações aqui previstas.<br/>
 <br/>
 <br/>
1. Informações de Conhecimento da Comunidade em Geral e Manifestações dos Visitantes do Website<br/>
 <br/>
1.1 Navegação livre e sem necessidade de cadastro<br/>
1.1.1 Qualquer pessoa que acessar o RECORRENTE poderá navegar por algumas de suas páginas sem se cadastrar. Para acessar alguns locais específicos do website, será necessário fazer um cadastro.<br/>
<br/>
1.1.2 Quando o usuário não estiver cadastrado e "logado", o RECORRENTE não recolherá nenhum tipo de dado de seu perfil.<br/>
 <br/>
1.2 Informações de Conhecimento da Benfeitoria<br/>
1.2.1 A Benfeitoria terá conhecimento de todos dados fornecidos através do seu website (exceto a senha dos usuários cadastrados), bem como de todo conteúdo das ações e transações feitas através do site. Não será de seu conhecimento, todavia, qualquer informação relativa os dados bancários ou de cartão de crédito informados ao MoiP para fins de efetivação da colaboração. Tais informações são de conhecimento exclusivo do MoiP.<br/>
 <br/>
 <br/>
1.3 Informações que serão de Conhecimento dos Colaboradores<br/>
1.3.1 Além de todas as informações públicas do website, os colaboradores podem solicitar o CPF ou CNPJ do Realizador para fins de declaração de imposto de renda, quando for o caso.<br/>
 <br/>
1.3.2 Os Colaboradores reconhecem que seu apelido e foto (se enviada) serão publicados na aba “Assinantes” da página da campanha para o qual contribuiu.<br/>
 <br/>
 <br/>
1.4 Informações que serão de Conhecimento dos Realizadores<br/>
1.4.1 Além de todas as informações públicas do website, o Realizador também será informado todo mês sobre os nomes e e-mails de todos Colaboradores de sua campanha.<br/>
 <br/>
1.4.2 Os Realizadores reconhecem que qualquer visitante do RECORRENTE tomará conhecimento do conteúdo de ssua campanha e que poderá fazer comentários, curti-lo ou denunciá-lo. A Benfeitoria não fará controles prévios das manifestações dos visitantes no website. Caso algum Realizador sinta-se desconfortável com qualquer manifestação dos Usuários na área de Comentários do seu projeto, poderá solicitar a exclusão da mesma.<br/>
 <br/>
1.5 Informações que serão de conhecimento de Visitantes (cadastrados ou não)<br/>
Serão de conhecimento de qualquer pessoa que acesse o RECORRENTE as informações públicas disponíveis no website, disponíveis na página das campanhas (tais como material de apresentação, metas e recompensas, número de apoiadores, valor arrecado em tempo real, nome e foto dos apoiadores, novidades, prestações de conta e comentários publicados) e na página perfil dos usuários cadastrados (tais como nome, apelido, foto, texto do perfil, campanhas publicadas, colaborações para outras campanhas).<br/>
 <br/>
 <br/>
1.6 Informações que serão de conhecimento de Parceiros da Benfeitoria<br/>
1.6.1 Poderão ser de conhecimento dos Parceiros da Benfeitoria, além das informações que qualquer visitante do site terá acesso, apenas os números relativos às operações do website (número de acessos, quantidade de participantes etc.). Não compartilharemos dados pessoais de nenhum usuário do site com nenhum parceiro, em hipótese alguma.<br/>
 <br/>
 <br/>
1.7 Abrangência das regras de Privacidade<br/>
1.7.1 Essas regras sobre privacidade se aplicam apenas ao site do RECORRENTE. Elas não valem para sites indicados por meio de links. Você deve se informar sobre a política de cada um deles antes de fornecer qualquer tipo de informação.<br/>
 <br/>
2. Alteração da Política de Privacidade<br/>
2.1 Esta Política de Privacidade pode ser alterada periodicamente. Esta Política de Privacidade não reduzirá os seus direitos sem o seu consentimento explícito. Publicaremos todas as alterações da Política de Privacidade nesta página e, se as alterações forem significativas, colocaremos um aviso com mais destaque no site.<br/>
 </div><!-- /.pagePadrao -->s

              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
