<!DOCTYPE html>
<!--[if IE 8]>			<html class="ie ie8"> <![endif]-->
<!--[if IE 9]>			<html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->	<html> <!--<![endif]-->
<head>

	<!-- Basic -->
	<meta charset="utf-8">
	<title>Xmile.com.br</title>
	<meta name="keywords" content="HTML5 Template" />
	<meta name="description" content="">

        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="apple-touch-icon-144x144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png">
    
        <!-- Mobile Metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href='http://fonts.googleapis.com/css?family=Dosis&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="/css3/bootstrap/bootstrap.css" />
    
        <!-- AWESOME and ICOMOON fonts -->
        <link rel="stylesheet" href="/fonts/awesome/css/font-awesome.css">
        <link rel="stylesheet" href="/fonts/icomoon/style.css">
    
        <!-- Theme CSS -->
        <link rel="stylesheet" href="/css3/theme.css">
        <link rel="stylesheet" href="/css3/theme-elements.css">
        <link rel="stylesheet" href="/css3/color/orange.css">
        <link rel="stylesheet" type="text/css" href="/css3/xmile.css">
        <!-- Modernizr -->
        <script type="text/javascript" src="/js/modernizr/modernizr.js"></script>
        <script src="/js/skrollr.js"></script>
        <!-- Add fancyBox main JS and CSS files -->
        <script type="text/javascript" src="/js/modal/jquery.fancybox.js?v=2.1.5"></script>
        <link rel="stylesheet" type="text/css" href="/js/modal/jquery.fancybox.css?v=2.1.5" media="screen" />

        <!-- Add Media helper (this is optional) -->
        <script type="text/javascript" src="/js/modal/helpers/jquery.fancybox-media.js?v=1.0.6"></script>

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<script src="/js/scroll/jquery.mCustomScrollbar.concat.min.js"></script>
		<link href="/js/scroll/jquery.mCustomScrollbar.css" rel="stylesheet" />
		<script src="/js/main.js"></script>
		<script type="text/javascript" src="/js/flip3d/jquery.easing.1.3.js"></script>	
        <script type="text/javascript" src="/js/flip3d/modernizr.2.5.3.min.js"></script>  
		<script type="text/javascript" src="/js/jgestures.min.js"></script>
</head>
<body class="page-features">
 <section id="containerInside">   
        <div class="container">
          <div class="push push-big"></div>
            <div class="row">
              <div class="alert alert-success animated">
                <div class="success-heading">
                  <h4>
                    <i class="fa fa-exclamation-triangle"></i><span> Aviso</span>
                  </h4>
                </div>
								<h5 style="color:#FFFFFF;"><?php echo $sMensagem ?>.</h5>
              </div>
            <a href="/seguro/recuperarSenha" class="contactWorkButton">Voltar</a>
            </div>
			<div class="push push-big"></div>
            <div class="push push-big"></div>
            <div class="push push-big"></div>
            <div class="push"></div>
       </div>
  </section>                     
	<!-- jQuery & Helper library -->
	<script type="text/javascript" src="/js/library/jquery/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="/js/library/helper/jquery.easing.min.js"></script>
	<script type="text/javascript" src="/js/library/helper/jquery.touchSwipe.min.js"></script>
	<script type="text/javascript" src="/js/library/helper/jquery.mousewheel.min.js"></script>
	<script type="text/javascript" src="/js/library/helper/imagesloaded.pkgd.min.js"></script>
	<script type="text/javascript" src="/js/library/smoothScroll/SmoothScroll.js"></script>

	<!-- Retina js -->
	<script type="text/javascript" src="/js/library/retina/retina.js"></script>

	<!-- FancyBox -->
	<script type="text/javascript" src="/js/library/fancybox/jquery.fancybox.pack.js?v=2.1.5"></script>

	<!-- Bootstrap js -->
	<script type="text/javascript" src="/js/library/bootstrap/bootstrap.min.js"></script>

	<!-- carouFredSel -->
	<script type="text/javascript" src="/js/library/carouFredSel/jquery.carouFredSel-6.2.1-packed.js"></script>

	<!-- Validate -->
	<script type="text/javascript" src="/js/library/validate/jquery.validate.min.js"></script>

	<!-- FlickrFeed  -->
	<script type="text/javascript" src="/js/library/jFlickrFeed/jflickrfeed.min.js"></script>

	<!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
	<script type="text/javascript" src="/js/library/slider-revolution/js/jquery.themepunch.plugins.min.js"></script>
	<script type="text/javascript" src="/js/library/slider-revolution/js/jquery.themepunch.revolution.min.js"></script>

	<!-- Scripts for current page -->
	<script type="text/javascript" src="/js/page/home.js"></script>

	<!-- Main theme javaScript file -->
	<script type="text/javascript" src="/js/theme.js"></script>
</body>
</html>
