<div id="modalTermosUso" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalTermosUso" aria-hidden="true">
  <div class="modal-header">
   <h3>Termos de Uso</h3>
  </div>
  <div class="modal-body">
    <p>
    <div style="height:400px;overflow-y:auto">
    
TERMOS E CONDIÇÕES DE CONTRATAÇÃO DE ASSINATURAS<br/>
<br/>
São partes neste instrumento, de um lado, BENFEITORIA MIRABOLANTE - SERVIÇOS CRIATIVOS NA INTERNET LTDA, empresa legalmente constituída, com sede na Avenida São Sebastião, nº 18/101, Urca, Rio de Janeiro, inscrita no CNPJ/MF sob número 12.909.805/0001-31, doravante identificada simplesmente como BENFEITORIA e, de outro lado, a pessoa física ou jurídica identificada no Cadastramento Eletrônico pelo seu Código de Assinatura, doravante identificada simplesmente como ASSINANTE,<br/>
<br/>
1. OBJETO DOS TERMOS E CONDIÇÕES. O presente instrumento tem por objeto estabelecer os termos e condições da contratação celebrada entre a BENFEITORIA (Contratada) e o ASSINANTE (Contratante) caracterizada pelo apoio financeiro continuo a iniciativas publicadas na plataforma RECORRENTE.<br/> 
1.1 As informações encontram-se disponíveis ao ASSINANTE no site <a href="http://recorrente.benfeitoria.com/comoFunciona" target="_blank">recorrente.benfeitoria.com/comoFunciona</a>.<br/>
<br/>
2. CÓDIGO DA ASSINATURA: A BENFEITORIA concederá ao ASSINANTE um “Código Único de Usuário” para identificação do ASSINANTE junto ao Serviço de Atendimento ao Cliente, que será um código pessoal e intransferível com até quatro dígitos. O ASSINANTE pode encontrá-lo após a confirmação do seu pedido na própria plataforma e no e-mail de confirmação de contratação de assinatura.<br/>
<br/>
3. ENTREGA A entrega do Serviço se iniciará no prazo máximo de 24 horas a contar da data da contratação.<br/>
3.1. Para que o prazo de início da entrega do Serviço seja observado, o ASSINANTE deverá informar de maneira completa todos os dados de seu endereço:<br/>
a) Logradouro (Ex.: rua, avenida, praça, etc.);<br/>
b) Número do imóvel; <br/>
c) Eventual complemento (Ex.: apto., casa, fundos, baixos, etc.);<br/> 
d) bairro; <br/>
e) Cidade; <br/>
f) Estado; <br/>
g) Código de Endereçamento Postal – CEP.<br/>
<br/>
4. CONTRATAÇÃO, PREÇOS, FORMAS DE PAGAMENTO: A contratação pelo ASSINANTE deverá ser realizada por meio do “site” da BENFEITORIA: recorrente.benfeitoria.com <link>, onde constarão todos os Planos de Assinatura disponíveis, bem como suas condições específicas.<br/>
4.1. O ASSINANTE deverá optar pelo Plano de Assinatura que deseja contratar, sendo certo que suas condições específicas (Valores, Condições de Pagamento e etc.) constantes do site passarão a fazer parte integrante e inseparável do presente instrumento.<br/>
4.2. O ASSINANTE expressamente declara e garante, para todos os fins de direito: <br/>
(I) possuir capacidade jurídica para celebrar este instrumento e para utilizar o Produto/ Serviço; <br/>
(II) reconhecer que o presente instrumento se formaliza, vinculando as partes, com a confirmação contratual, o que se fará mediante o clique no espaço reservado para tanto no site da BENFEITORIA: <a href="http://recorrente.benfeitoria.com" target="_blank">recorrente.benfeitoria.com</a>.<br/>
4.3. Como contra prestação pelo objeto deste contrato, o ASSINANTE deverá pagar à BENFEITORIA a quantia correspondente ao Plano contratado, conforme opção realizada na hora da compra e vigente no ato da compra.<br/>
4.4. A forma de pagamento será escolhida pelo ASSINANTE dentre as constantes do “site” para o Plano escolhido, onde constarão também a periodicidade da cobrança e eventuais penalidades aplicáveis.<br/>
<br/>
5. BANCO DE DADOS. O ASSINANTE se declara ciente de que, a partir da contratação da assinatura de um Produto/Serviço, o mesmo passa a fazer parte do banco de dados da BENFEITORIA, por meio do qual poderá vir a receber informações da BENFEITORIA e das iniciativas publicadas no “site”. Se acaso o ASSINANTE não tiver o interesse em receber essas informações, fica assegurado ao mesmo o direito de manifestar sua oposição, bastando que tal decisão seja comunicada para o Serviço de Atendimento ao Cliente recorrente@benfeitoria.com.<br/>
5.1. A inviolabilidade e o sigilo dos dados cadastrais de todo os seus ASSINANTES são assegurados pela BENFEITORIA. Todas as suas informações são armazenadas dentro dos mais rígidos critérios de segurança no banco de dados da BENFEITORIA e são tratadas de acordo com a legislação aplicável. Em nenhuma hipótese são fornecidas informações pessoais para terceiros não relacionados à prestação dos serviços, objeto do presente instrumento, somente dados genéricos utilizados para envio de mala direta, e-mail, newsletters e desde que autorizado pelo ASSINANTE.<br/>
<br/>
6. SERVIÇO DE ATENDIMENTO AO ASSINANTE. A BENFEITORIA disponibiliza ao ASSINANTE Serviço de Atendimento e coloca à disposição os seguintes canais de contato:<br/>
a) Site: recorrente.benfeitoria.com<br/>
b) E-mail: recorrente@benfeitoria.com.<br/>
Periodicidade de funcionamento (dias e horários): Segunda à Sexta 10:00 - 20:00.<br/>
<br/>
7. PRAZO. Este instrumento é celebrado por prazo  indeterminado, sujeito a interrupção da contratação do serviço, conforme previsto no próximo item.<br/>
<br/>
8. CANCELAMENTO. A BENFEITORIA assegura ao ASSINANTE a possibilidade de cancelamento do presente instrumento a qualquer tempo por meio do <a href="http://recorrente.benfeitoria.com/usuario/pagamentos" target="_blank">recorrente.benfeitoria.com/usuario/pagamentos</a>.<br/>
<br/>
9. ALTERAÇÕES DOS TERMOS E CONDIÇÕES. Quaisquer alterações que impactem em ônus financeiro ao ASSINANTE, serão feitas mediante comunicação prévia ao mesmo, que poderá manifestar a sua concordância, por qualquer meio disponível, renegociar tais alterações ou qualquer das partes poderá denunciá-lo, caso não cheguem a um acordo.<br/>
<br/>
10. FORO. Fica assegurado ao ASSINANTE o direito de, caso necessário, recorrer ao Foro da Comarca em que residir, para quaisquer dúvidas e questões oriundas deste instrumento.<br/>    
    
    </div>
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true" >Fechar</button>
  </div>
</div>
<!-- Fim da modal dos termos -->




            <strong class="headlineContribuicao">Assinatura</strong>
              
             <br />
            <span class='contribuicaoLogin assinatura'>
                Escolha o valor da sua assinatura mensal:
              </span>

            <div class="values">
<?php
    $aContributionOptions = $oProject->getAllContributionValuesTypes(); 
    foreach ($aContributionOptions as $aContributionOption) {
?>
                <button type="button" class="btn btn-success price" onClick="$('#freeValue').val('');$('#idContributionOption').val('<?php echo $aContributionOption["id_contribution"]?>');$('#contributionValue').val('<?php echo $aContributionOption["value"]?>');$('#contributionValue').html('<?php echo "R$ ".number_format($aContributionOption["value"],0,",",".")?>'); $('#divConfirm').show()">R$ <?php echo number_format($aContributionOption["value"],2,",",".");?></button>
<?php
    }
?>  
            </div>

            <br>

            <p class='info'>
                ou informe outro valor desejado: 
              </p>

              <form action="" class="form-inline">
                <div class="input-prepend input-append">
                  <span class="add-on">R$</span>
                  <input class="span2" type="text" id="freeValue" onChange="if ($('#freeValue').val().replace('.','')>=10) { $('#divAvisoMaior10').hide(); $('#idContributionOption').val('0');$('#contributionValue').val($('#freeValue').val().replace(/\./g,''));$('#contributionValue').html('R$ '+$('#freeValue').val()); $('#divConfirm').show(); } else { $('#divAvisoMaior10').show(); $('#freeValue').focus(); } ">
                  <span class="add-on">,00</span>
                </div>
                <input type="button" class='btn btn-small' value='Ok'>
              </form>
              <div class="alert alert-danger" id="divAvisoMaior10" style="display:none">O valor precisa ser maior do que R$ 10,00</div>
              <div class="hide" style="display:none" id="divConfirm">
                <p class="info">Antes de continuar, verifique abaixo o valor escolhido e clique em CONFIRMAR.</p>

                <span class='valorFinal'><span class="" id="contributionValue"></span>/mês</span>
                <!-- <p class="info text-center">Contribuição mensal</p> -->
              <br>
                <form>
                    <input type="hidden" name="id_contribution_option" id="idContributionOption" value=""> 
                    <input type="hidden" name="id_contribution_old" id="idContributionOld" value="<?php echo $iIdContributionOld?>"> 
                    <input type="hidden" name="value" id="contributionValue" value="">
                </form>
           <!--    <a href="#modalTermosUso" role='button' data-toggle="modal"><button class="btn btn-danger confirmContri">Termos de Assinatura</button></a><br/> -->
           <em class='info'>Não tem fidelidade! Você pode cancelar ou modificar na hora que quiser!</em><br><br>
           <span class='confirmaLeituraTermo'><input type="checkbox" id="liTermos" />Confirmo que li os <a href="#modalTermosUso" role='button' data-toggle="modal">Termos de Assinatura</a></span>
              <br/>
              <a href="javascript:goCheckout()"><button class="btn btn-primary confirmContri" id="btnConfirmar" disabled>Confirmar</button></a>
              </div>
              
              
<script>
    $(".loader").fadeOut('fast');
    $('#freeValue').maskMoney({allowNegative: false, thousands:'.', decimal:',', affixesStay: false, precision:0});
    
    function goCheckout() {
        var iIdContributionOption = $('#idContributionOption').val();
        var sContributionValue = $('#contributionValue').val();
        var iIdContributionOld = $('#idContributionOld').val();
        
        $('#divConteudo').fadeOut('slow', function(){
        	// $(".loader").fadeIn('fast');
   	    });
    		$.ajax({
    			  type: 'POST',
    			  url: sBasePath+'/projeto/ajaxIniciaContribuicao',
    		    data: {contributionOption: iIdContributionOption, contributionValue: sContributionValue, projectId: '<?php echo $oProject->getId() ?>', contributionOld: iIdContributionOld},
    			  dataType: 'json',
    		    cache: false,
    			  timeout: 8000,
    			  success: function(json) {
    				  if (json.retorno=='ok') {
    				    // Envia para o seletor de cartão
    					  $('#divConteudo').load(sBasePath+'/projeto/ajaxContribuicaoP2/<?php echo $oProject->getId() ?>-'+json.id_contribuicao+'-'+iIdContributionOld, function(){
                    // $(".loader").fadeOut('fast', function(){ $('#divConteudo').fadeIn(); });
    					  		$('#divConteudo').fadeIn();
    					  });
    				  }
    				  else {
    					  $('#divConteudo').load(sBasePath+'/projeto/ajaxMensagem/erro-cria-contribuicao', function(){
    					  		$(".loader").fadeOut('fast', function(){ $('#divConteudo').fadeIn(); });
    					  });
    				  }
    			  },
    			  error: function (jqXHR, textStatus, errorThrown) {
    			  	switch (textStatus) {
    				  	case 'timeout'	:	alert('Timeout...');
    				  										break;
    				  	default         : alert('Erro!\n\n'+errorThrown);
    				  										break;
    			  	}
    			    return false;
    		  	}
    		});
    }
     
</script>              